// Versie van het spel. Semantisch: MAJOR.MINOR.PATCH.
// Elke laag verhoogt MINOR, kleine correcties verhogen PATCH.

export const VERSION = '0.80.0';

export interface ChangeEntry {
  version: string;
  date: string;
  title: string;
  items: string[];
}

export const CHANGELOG: ChangeEntry[] = [
  {
    version: '0.80.0',
    date: '2026-09-25',
    title: 'Add test.txt to workflows directory',
    items: [
      'Add test.txt to workflows directory',
    ],
  },
  {
    version: '0.79.7',
    date: '2026-09-25',
    title: 'Update release workflow for better version handling',
    items: [
      'Update release workflow for better version handling',
    ],
  },
  {
    version: '0.79.6',
    date: '2026-09-25',
    title: 'Het loonvoorstel springt niet meer heen en weer',
    items: [
      'Elke rij op Contracten gokte tot nu toe zelf hoe breed haar loonveld moest zijn (tien keer haar eigen voorstel); bij een lager bedrag dan de rij erboven kroop de knop ernaast dus naar binnen. Nu delen alle rijen in een tabel hetzelfde plafond: de hoogste vraag in je selectie',
    ],
  },
  {
    version: '0.79.5',
    date: '2026-09-25',
    title: 'Cloudflare-previewbuild kreeg geen previews-blok',
    items: [
      'De Cloudflare-buildstap draait `npx wrangler preview` voor PR-previews; zonder een (leeg mag) previews-blok in wrangler.jsonc weigerde die stap meteen, dus faalde elke preview-deploy nog voor de app zelf gebouwd werd',
    ],
  },
  {
    version: '0.79.4',
    date: '2026-09-25',
    title: 'De spelplan-stap in de rondleiding vinkt af bij een bezoek',
    items: [
      'Rondkijken bij Ploeg › Strategie vinkte de stap "kies een spelplan" niet af, want het beginplan (balbezit) staat al gekozen — je moest eerst zelf wisselen om ze kwijt te raken',
      'Een bezoek is nu genoeg, net als bij de andere kijk-stappen; de tekst wijst je erbij op het scoutingrapport en de sterk/zwak-matchup tegenover je volgende tegenstander',
    ],
  },
  {
    version: '0.79.3',
    date: '2026-09-25',
    title: 'Drie tabellen, één kolomlijn — en huurspelers als echte rij',
    items: [
      'Alle tabellen op Contracten delen nu vaste kolombreedtes: Pos, Speler, Kwal/Pot en Contract staan pixelgelijk onder elkaar',
      'De huurspelers zijn een rij in dezelfde tabel-huisstijl geworden: positie, statistieken, kwaliteit, eigenaar met tevredenheid, en twee compacte biedkolommen',
    ],
  },
  {
    version: '0.79.2',
    date: '2026-09-25',
    title: 'Kwaliteit op de huurspelerkaart in de huisstijl',
    items: [
      'Het kwaliteitscijfer staat er nu zoals overal in de tabellen: vet, met het potentieel gedempt erachter (51 / 66)',
    ],
  },
  {
    version: '0.79.1',
    date: '2026-09-25',
    title: 'De huurspelerkaart vertelt wie je verlengt',
    items: [
      'De kopregel toont nu positie en kwaliteit/potentieel, zoals bij je eigen contracten — je wist amper wát je aan het verlengen was',
      'Bedrag, kans en knop staan compact op één rij: geen invoervelden en knoppen op bannerformaat meer',
    ],
  },
  {
    version: '0.79.0',
    date: '2026-09-25',
    title: 'Wat is er nieuw — de changelog in het spel',
    items: [
      'Onder Menu staat nu "Wat is er nieuw": elke versie in gewone taal, nieuwste bovenaan',
      'Alles wat jij nog niet bekeek draagt een badge "nieuw voor jou", en er staat een stip op het menu zolang er iets ongezien is',
      'Eén knop markeert alles als gezien (per toestel onthouden) — handig om bij te houden wat je al testte',
    ],
  },
  {
    version: '0.78.0',
    date: '2026-09-25',
    title: 'Alles over wie blijft, op één scherm',
    items: [
      'Contracten is nu dé thuisbasis: "Eigen spelers: aflopende contracten", "Eigen spelers: rest van de kern" en "Huurspelers: houden of kopen" als drie heldere kaarten',
      'De huurkaart is weg van Transfers; daar staat een wegwijzer zolang je huurlingen hebt',
      'De handleiding wijst mee naar de nieuwe plek',
    ],
  },
  {
    version: '0.77.2',
    date: '2026-09-25',
    title: 'Het contractenscherm krijgt de ruimte',
    items: [
      'De twee kaarten stonden op halve breedte naast elkaar terwijl hun tabellen zeven kolommen plus biedveld plus twee knoppen dragen: "Dit bod doen" brak over drie regels',
      'Beide kaarten staan nu op volle breedte onder elkaar, en knopteksten in tabellen breken nooit meer',
    ],
  },
  {
    version: '0.77.1',
    date: '2026-09-25',
    title: 'De transfermarkt-stap vinkt weer af',
    items: [
      'Sinds kopen een gesprek van een week is, zag de rondleidingsstap je aankoop niet meer — en "kijk rond" eiste stiekem een transactie',
      'Het scherm bezoeken is nu genoeg, en een lopend koop- of huurgesprek telt ook',
    ],
  },
  {
    version: '0.77.0',
    date: '2026-09-25',
    title: 'Kopen en huren is een gesprek, en "niet verlengen" bestaat',
    items: [
      'Je maakt je interesse over en de spéler beslist: het antwoord komt een week later, in je nieuwsstroom en je weekverslag (tekenen = vieringskaart)',
      'Zolang het gesprek loopt is hij gereserveerd — van de markt, zichtbaar bij "wacht op antwoord" op je Bureau en "Loopt nog" in het verslag',
      'Uitzondering: zit je kern onder de elf, dan tekent hij meteen — geen wachtweek naast een dreigende forfait',
      'Bij aflopende contracten kun je nu "Niet verlengen" kiezen: hij verdwijnt uit je waarschuwingen en lijstjes, en vertrekt op het einde van het seizoen (bedenken mag)',
    ],
  },
  {
    version: '0.76.0',
    date: '2026-09-25',
    title: 'De trainerscarrousel draait — ook bij de andere clubs',
    items: [
      'Ontsla je je hoofdtrainer, dan is dat dorpsnieuws in je nieuwsstroom',
      'En elders in de reeks rollen er nu ook koppen: clubs onderin zetten al eens een trainer op straat, met een opvolger die meteen op het oefenveld staat',
      'Pure vertelling — de sterkte van tegenstanders verandert er niet door, maar de reeks leeft',
    ],
  },
  {
    version: '0.75.0',
    date: '2026-09-25',
    title: 'Bankteller op Selectie, en van een bod rechtstreeks naar de speler',
    items: [
      'Naast "Je kern" staat nu 🔁 X/5: hoeveel bankplaatsen je hebt ingevuld, met per linie een teller in de kopjes — vier keepers op de bank valt meteen op',
      'De spelersnaam in een bod is klikbaar: je springt naar zijn rij in de kernlijst, die even oplicht — zo schat je meteen in wie je zou kwijtraken',
    ],
  },
  {
    version: '0.74.3',
    date: '2026-09-25',
    title: 'Huurspelers horen niet bij "contracten lopen af"',
    items: [
      'Een huurspeler stond in de waarschuwing en de aflooplijst, maar verlengen ketste af op "hij is gehuurd" — dubbel en verwarrend',
      'Huurlingen staan nu nergens meer tussen de aflopende contracten (ook niet in het week-40-nieuws of bij je uitbestede onderhandelaar)',
      'De kaart "huurspeler houden" (verlengen of kopen, met de eigenaar) staat voortaan óók op het Contracten-scherm',
    ],
  },
  {
    version: '0.74.2',
    date: '2026-09-25',
    title: 'Een rondleidingsstap blijft afgevinkt',
    items: [
      'De sponsorstap sprong weer open als het benaderde bedrijf een week later weigerde — alsof je niets gedaan had',
      'Eenmaal afgevinkte stappen blijven nu afgevinkt, vastgelegd op het moment van je actie',
    ],
  },
  {
    version: '0.74.1',
    date: '2026-09-24',
    title: 'Pixels op hun plek, en navigeren begint bovenaan',
    items: [
      'Prijzen en knoppen op kaarten in één rij hingen tot 49 pixels uit elkaar: de prijs-en-knop-cluster zit nu onderaan elke kaart vastgepind',
      'Sluit een kaart af met een tekstregel in plaats van een knop, dan krijgt die regel knophoogte — geen verspringende prijzen meer',
      'Wissel je van scherm (ook via de Bureau-knop), dan begin je bovenaan in plaats van ergens midden in de vorige scrollpositie',
    ],
  },
  {
    version: '0.74.0',
    date: '2026-09-24',
    title: 'Volwaardig op de iPad, zonder één pixel verschil op de pc',
    items: [
      'Alle tikdoelen naar minstens 40 pixels: tabs, subtabs, vraagtekens, plus/min-knoppen, sterren, wisselbank en sponsorfilters (gemeten: 20 schermen × 2 oriëntaties, alles groen)',
      'Invoervelden naar 16 pixels op aanraakschermen, zodat iPadOS niet meer inzoomt bij focus',
      'Het plakkende hover-effect na een tik is geneutraliseerd, overlays volgen de echte schermrand (dvh) en de speelbalk ontwijkt de thuisbalk',
      'Alles zit achter (pointer: coarse) en (hover: none): met een muis verandert er niets — nagemeten',
    ],
  },
  {
    version: '0.73.0',
    date: '2026-09-24',
    title: 'Een vaste weg naar het Bureau, en Selectie in balans',
    items: [
      'De tijdelijke terugknop van de rondleiding is een vaste "🏠 Bureau"-knop geworden, naast de speelknoppen (behalve op het Bureau zelf)',
      'Tijdens de rondleiding stuitert het vingertje erboven — daar wacht je volgende stap',
      'De sterkte-uitsplitsing en Spelersrollen staan nu ónder het veld: de lege vlakte naast de lange kernlijst is weg',
    ],
  },
  {
    version: '0.72.1',
    date: '2026-09-24',
    title: 'Kraampjes verdienen zichzelf nu in twintig weken terug',
    items: [
      'Twee seizoenen terugverdientijd was netjes realistisch en precies daarom fout: investeren moet een rush geven',
      'De prijs rekent nu met 22 weken (gemeten: ±19 in de praktijk) — het spel mag geen grind worden',
    ],
  },
  {
    version: '0.72.0',
    date: '2026-09-24',
    title: 'Kraampjesplaatsen bijbouwen',
    items: [
      'Nieuw bouwproject bij 💶 Investeringen: een extra plaats voor een standhouder (van 3 naar maximaal 6)',
      'De prijs volgt je opkomst en is gemeten op een terugverdientijd van ±1,7 seizoen — een degelijke investering, geen gratis geld',
      'Zit je horeca vol, dan wijst het scherm je nu de weg naar de bouwkaart',
    ],
  },
  {
    version: '0.71.0',
    date: '2026-09-24',
    title: 'Selectie opgeruimd: minder dubbel, meer ruimte, duidelijker bank',
    items: [
      'De bankknop is nu overal 🔁 (het stoeltje is weg) en een bankspeler kleurt amber',
      'Het veld is breder en ruimer, en de kernlijst groeit mee met je scherm in plaats van te scrollen in een korte kaart',
      'Weg wat dubbel stond: de sterktetegels (de banner boven het veld toont ze al), de linietegels (staan op het veld zelf) en de kaarten-weergave van de kern (het zijpaneel toont dezelfde spelers)',
      'Wat bleef is uniek: de speelklaar-teller, "Waar je sterkte vandaan komt" (de bonussen-uitsplitsing) en de sorteerbare cijfertabel',
    ],
  },
  {
    version: '0.70.0',
    date: '2026-09-24',
    title: 'De rondleiding wijst nu ook vooruit',
    items: [
      'Hoofdstuk af? Dan hangt er een tekstballon met wijsvinger boven "Volgende week": speel gerust een weekje — daarna ligt het volgende hoofdstuk klaar',
      'Zolang er stappen openstaan, wijst er een vingertje naast "Leer je club kennen" op je Bureau',
    ],
  },
  {
    version: '0.69.1',
    date: '2026-09-24',
    title: 'De wisselbank legt zichzelf uit',
    items: [
      'Nieuwe handleidingsvraag "Hoe werkt de wisselbank?" met het volledige verhaal: wie invalt, wat het kost, waarom het je beloften laat groeien, en de keerzijde',
      'De basiself-vraag in de handleiding beschreef nog de oude uitsluitknop — rechtgezet',
      'Een hint bij de bankregel op Selectie en een rijkere spelerskaart-tip, kort genoeg om in één keer te lezen',
    ],
  },
  {
    version: '0.69.0',
    date: '2026-09-24',
    title: 'Een echte wisselbank: invallers spelen, groeien en tellen mee',
    items: [
      'Duid tot vijf bankspelers aan (🔁 op Selectie); tijdens de wedstrijd vallen er één tot drie van hen in, nooit de doelman eruit',
      'Invallers tellen minuten-gewogen mee in de sterkte, gecentreerd rond het gemeten trainersgemiddelde (−0,45): een gewone bank is neutraal, een sterke levert op, beloften kosten een beetje',
      'Een invalbeurt telt als minuten plus wedstrijdritme in het speelaandeel: een diepe reserve op de bank groeit nu méér dan vrij meetrainen (gemeten: +1,00 tegenover +0,83 over 24 weken)',
      'Invallers kunnen scoren (pas na hun invalminuut), pakken kaarten, delen in de winstpremie (de helft) en worden naar minuten moe',
      'De wissels in de wedstrijdtijdlijn zijn nu écht — de belofte uit 0.56.0 is ingelost; de oude 🪑-uitsluitknop is vervangen door de bank',
    ],
  },
  {
    version: '0.68.2',
    date: '2026-09-24',
    title: 'De tribune-kaart doet niet meer alsof ze gekozen is',
    items: [
      'De groene achtergrond was een overblijfsel van toen ze een eigen rij had — en groen betekent elders "geselecteerd"',
      'Ze is nu gewoon een witte kaart tussen de andere projecten',
    ],
  },
  {
    version: '0.68.1',
    date: '2026-09-24',
    title: 'De rondleiding heeft een terugweg',
    items: [
      'Bracht een stap je naar een scherm, dan hangt er nu in de speelbalk een pil "📚 volgende stap → je Bureau"',
      'Hij verschijnt alleen onderweg en lost vanzelf op zodra je terug op je Bureau bent (of de rondleiding wegklikt)',
    ],
  },
  {
    version: '0.68.0',
    date: '2026-09-24',
    title: 'Elke bouwcategorie zijn eigen kaart',
    items: [
      'De vijf categorieën waren kopjes binnen één lange kaart en dat las als één brij: nu is elke categorie een echte kaart',
      'De tribune met haar schuif nam een hele rij in beslag: ze is nu een dubbelbreed kaartje in het Ruwbouw-raster, naast kantine en toiletten',
      'Een smalle intro-balk erboven houdt de spelregels (hoeveel werven tegelijk, leningen, aannemerskorting)',
    ],
  },
  {
    version: '0.67.0',
    date: '2026-09-24',
    title: 'De rondleiding durft er te staan',
    items: [
      'Het blok was zo kalm dat het als optioneel voetnootje las: nu een paneel in de clubkleur, zelfde taal als de persconferentie',
      'Elke open stap heeft een echte groene knop in plaats van een tekstlinkje',
      'De routekaart onderaan toont wat nog komt (markt → mensen → geld → clubzaken → vooruitkijken) — de rondleiding gaat dus wél over de hele club, niet alleen de ploeg',
      '"Ik ken het spel al" blijft, iets beter leesbaar',
    ],
  },
  {
    version: '0.66.0',
    date: '2026-09-24',
    title: 'De seizoensopening ademt, en de keuze maakt zich bekend',
    items: [
      'De persconferentie staat nu in de clubkleur met de badge "kies om te starten" — het was even grijs als de achtergrondinfo erboven, terwijl het de enige weg vooruit is',
      'Elke uitspraak heeft een echte knop "Dit zeg ik ▸", en de tekst zegt letterlijk dat je keuze het seizoen start',
      'Meer lucht in het hele scherm: ruimere tussenafstanden, hogere regelafstand, kortere belofteregels',
    ],
  },
  {
    version: '0.65.0',
    date: '2026-09-24',
    title: 'Het bouwscherm in balans, en vier projecten in plaats van twee combi\'s',
    items: [
      'De bouwkaart hing halfbreed en scheef naast twee smalle kaartjes: nu twee halve kaarten bovenaan en de projecten over de volle breedte, per groep gelijkmatig gevuld',
      'Toiletten (€30.000) en kleedkamers (€38.000) zijn aparte projecten: toiletten trekken gezinnen en kantineomzet, kleedkamers maken het complex verzorgd en je vrijwilligers trots',
      'Zonnepanelen (−14% vaste kosten) en ledverlichting (−6%, klaar in twee weken) zijn ook gesplitst: je kunt nu klein groen beginnen',
      'Wie de oude combi\'s al had, krijgt bij het laden gewoon beide helften',
    ],
  },
  {
    version: '0.64.0',
    date: '2026-09-24',
    title: 'De rondleiding neemt je bij het handje',
    items: [
      'Klik op een stap en de plek waar je moet zijn krijgt een omlijning in de clubkleur met een stuiterend handje erboven',
      'De basiself-stap was niet afvinkbaar zonder trucje (er staat al een elf klaar): kijken is nu genoeg, en de tekst legt uit dat de trainer kiest tot jij vastzet',
      'Vink je een stap af, dan hoor je het meteen: een toast zegt hoeveel er nog resten in het hoofdstuk — ook als je niet op je Bureau staat',
      'Hoofdstuk helemaal klaar? Ook dat meldt zich, met de belofte dat het volgende er volgende week ligt',
    ],
  },
  {
    version: '0.63.0',
    date: '2026-09-24',
    title: 'Shirts met spelersnamen: de tribune kiest haar lieveling',
    items: [
      'Wie een wedstrijdshirt koopt, laat er tegen €12 meerprijs een spelersnaam op drukken',
      'Welke naam, dat beslist de tribune: basisplaatsen tellen, doelpunten dubbel, een sterspeler verkoopt dubbel zo goed, eigen jeugd heeft streekwaarde',
      'De clubwinkel toont de top vijf met een 👑 voor de publiekslieveling — je populariteitspeiling in het echt, elk seizoen opnieuw',
      'Een nieuwe nummer één is dorpsnieuws, en de topnaam van vorig seizoen blijft in het clubgeheugen hangen',
    ],
  },
  {
    version: '0.62.0',
    date: '2026-09-24',
    title: 'De bouwprojecten in vijf herkenbare groepen',
    items: [
      'Twaalf werven stonden in één vlakke lijst: beton naast wifi naast een bus',
      'Nu vijf groepen zoals een bestuur erover praat: 🧱 Ruwbouw (tribune, kantine, sanitair, parking), ⚽ Sportief (kunstgras, verlichting), 🚪 Afdelingen (opleidingscentrum, recuperatie), 📡 Technologie (wifi, scorebord), 💶 Investeringen (ploegbus, zonnepanelen)',
      'Elke groep met één zin die zegt wat je er koopt; de groep staat in de catalogus, dus elk toekomstig project moet er een kiezen',
    ],
  },
  {
    version: '0.61.0',
    date: '2026-09-24',
    title: 'Eén rondleiding in plaats van twee lijsten',
    items: [
      '"Eerste stappen" en "Deze week" zijn samengevoegd: de rondleiding woont nu rustig onderin de weekkaart',
      'Zes hoofdstukken die elk één thema bundelen: je ploeg, de markt, je mensen, het geld (mét lidgeld en ticketprijzen), de clubzaken, vooruitkijken',
      'Eén hoofdstuk tegelijk; af = volgende week het volgende, blijven liggen = na drie weken zachtjes door — hulp, geen huiswerk',
      'Kijk-stappen (prijzen, bouwplannen, doelen, invloeden) vinken af zodra je het scherm bezoekt',
      'De rondleiding telt niet mee in "wat op je wacht", en "Ik ken het spel al" haalt hem definitief weg',
    ],
  },
  {
    version: '0.60.3',
    date: '2026-09-24',
    title: 'Ook een verkoop en een huurspeler zijn een feestje',
    items: [
      'Een speler verkopen (op de markt of via een bod) geeft nu de feesttoast: 💰 met naam en bedrag',
      'Een huurspeler die akkoord gaat komt binnen met 🖊️, zijn club en zijn loon',
      'Zegt de eigenaar een week later ja op verlengen of definitief kopen, dan staat dat als gouden kaartje in het weekrapport',
    ],
  },
  {
    version: '0.60.2',
    date: '2026-09-24',
    title: 'De feestkaartjes mogen gezien worden',
    items: [
      'Dikkere gouden rand, verzadigder goudverloop, een gloed eromheen, groter icoon en vetter lettertype',
      'Na het oppoppen trekt er één keer een glansveeg over de kaart — feest, geen paniek',
      'De pop-in veert nu ook licht door; bij animaties uit of verminderde beweging staat alles er gewoon meteen',
    ],
  },
  {
    version: '0.60.1',
    date: '2026-09-24',
    title: 'De kernlijst staat weer recht',
    items: [
      'De tekens naast een naam (sterspeler, kernspeler, kapitein, strafschop- en hoekschopnemer) kregen elk een eigen regel: de rij werd een toren en drukte de buren scheef',
      'Naam en tekens staan nu samen op één regel, elke rij is weer even hoog',
    ],
  },
  {
    version: '0.60.0',
    date: '2026-09-24',
    title: 'De kopbalk is minder kaal',
    items: [
      'Een vleug clubkleur achter je logo, die naar rechts wegloopt — warmte, geen behang',
      'Nieuw blokje Vorm: je laatste vijf uitslagen als stippen (groen gewonnen, grijs gelijk, rood verloren, hol nog te spelen), oudste links',
      'De tooltip vertelt elke uitslag voluit, en klikken brengt je naar de competitiestand',
    ],
  },
  {
    version: '0.59.0',
    date: '2026-09-24',
    title: 'De werklijst-pil valt nu echt op',
    items: [
      '"X dingen wachten op jou" stond in dezelfde zachte kleur als de rest van de balk en viel weg naast de grote weekknop',
      'De pil draagt nu het aandacht-palet: amber met het aantal in een echte badge, en rood zodra er iets dringends tussen zit',
      'Een trage polsslag rond de badge trekt het oog zonder te storen (uit bij verminderde beweging), en een pijltje toont dat je erop kunt klikken',
    ],
  },
  {
    version: '0.58.1',
    date: '2026-09-24',
    title: 'Een week zonder wedstrijd zegt dat nu zelf',
    items: [
      'In de winterstop toonde de weekanimatie een leeg veld met een rollende bal — dat las als een kapotte wedstrijdanimatie',
      'Winterstop: besneeuwd veld, dwarrelende vlokken, geen bal, kop "❄️ Winterstop"',
      'Elke andere week zonder wedstrijd zegt het er nu gewoon bij: "Geen wedstrijd deze week"',
    ],
  },
  {
    version: '0.58.0',
    date: '2026-09-24',
    title: 'Kleine successen worden echt gevierd',
    items: [
      'Een speler die tekent of verlengt, een sponsor die tekent of verlengt, een nieuw personeelslid: een feesttoast in de clubkleur met een seconde confetti',
      'Successen die vanzelf gebeurden — een diploma, een afgerond bouwproject, een sponsor via je commerciële man, doorstromers uit de jeugd — krijgen gouden kaartjes in het weekrapport, maximaal drie, na de cijfers',
      'De knoppen "Netwerkavond" en "Sponsorbureau" staan nu bovenaan de Contacten-kaart in plaats van onder de tabel, waar je ze pas na scrollen zag',
      'Wie animaties uitzette, krijgt dezelfde kaarten zonder confetti en pop-in',
    ],
  },
  {
    version: '0.57.2',
    date: '2026-09-24',
    title: 'Een gewone bevestigingspopup in plaats van de dubbelklik',
    items: [
      'De tweede-klik-op-dezelfde-knop van 0.57.0 bleek niet het patroon dat mensen kennen',
      'Ingrijpende knoppen openen nu een kleine popup: de vraag met naam en bedrag, de gevolgen eronder, en Annuleren naast de rode actieknop',
      'Escape of ernaast klikken annuleert ook',
    ],
  },
  {
    version: '0.57.1',
    date: '2026-09-24',
    title: 'De wedstrijd in twee lanen',
    items: [
      'De affiche staat er nu echt: beide ploegen groot, jouw ploeg in de clubkleur, en bij een derby de vlag erbij',
      'De tijdlijn heeft twee lanen rond een middellijn: de thuisploeg links, de uitploeg rechts, de minuut in het midden',
      'Jouw doelpuntenmakers en wissels dragen de clubkleur — je hoeft geen namen te kennen om te zien van wie iets was',
      'Na het affluiten blijft de uitslag tweeënhalve seconde staan, en onderaan de lijst kwam extra lucht',
    ],
  },
  {
    version: '0.57.0',
    date: '2026-09-24',
    title: 'Ingrijpende knoppen vragen een tweede klik',
    items: [
      'Stopzetten, ontslaan, wegsturen, huur beëindigen en verkopen kleuren rood en zeggen in de uitleg wat de gevolgen zijn',
      'De eerste klik wapent de knop — hij kleurt vol rood en zegt wat er gebeurt ("Zeker? €1.360/week stopt") — pas de tweede klik voert uit',
      'Vier seconden niets doen of ergens anders klikken, en de knop staat gewoon terug',
      'Geen popup: hetzelfde patroon dat "nieuw spel" al had, nu overal waar een beslissing definitief is',
    ],
  },
  {
    version: '0.56.2',
    date: '2026-09-24',
    title: 'Even nagenieten na het affluiten',
    items: [
      'Na het affluiten blijft de uitslag nog anderhalve seconde staan voor het weekrapport opent',
      'Het kader is nog een derde groter, en die ruimte gaat naar leesbaarheid',
      'De tijdlijn leest als een wedstrijdverslag: minuten rechts uitgelijnd in hun kolom, gebeurtenissen links, tussenstanden in een eigen kolom aan de rechterrand',
    ],
  },
  {
    version: '0.56.1',
    date: '2026-09-24',
    title: '"Op tafel" heeft een vaste plek',
    items: [
      'De voorstellen die op je wachten staan altijd op dezelfde plaats: vol breed, direct onder de prijskaart — of er nu iets ligt of niet',
      'Een kaart die van plek wisselt naargelang haar inhoud, vind je nooit terug op automatisme',
      '"Nieuwe namen vinden" zit nu in de Contacten-kaart: wat het bureau vindt, komt in die lijst terecht',
    ],
  },
  {
    version: '0.56.0',
    date: '2026-09-24',
    title: 'De wedstrijd duurt vijf tellen, met klok, rust en wissels',
    items: [
      'De wedstrijdtijdlijn ging van drie naar vijf seconden, in een ruimer kader',
      'Een lopende klok telt de eerste helft naar 45, valt stil op "Rust" (met de ruststand), en telt dan door naar 90',
      'Bij het affluiten toont de klok de uitslag',
      'Wissels van beide ploegen staan in de tijdlijn, met echte namen van je bank en uit hun kern',
      'De wissels zijn vertelling: het echte wisselsysteem (bankspelers met speelminuten) staat op de planning',
      'Een week zonder wedstrijd houdt de korte animatie van vroeger',
    ],
  },
  {
    version: '0.55.0',
    date: '2026-09-24',
    title: 'Het sponsorscherm in de vorm van het personeelsscherm',
    items: [
      'Zelfde opbouw als Personeel: de prijskaart vol breed, daaronder links wat je hebt (sponsors) en rechts wat er speelt (op tafel, contacten, acties)',
      'De sponsortegels hebben vier vaste zones — kop, invoer, oordeel, notitie — die er ook staan als ze leeg zijn: alles lijnt uit, wat er ook in staat',
      'Compactere tabellen: het type staat bij de naam, budget en vrije plaats bij het bedrijf',
      'Het scherm werd er ook korter van: van 2.596 naar 2.230 pixels',
    ],
  },
  {
    version: '0.54.0',
    date: '2026-09-24',
    title: 'Het weekrapport bouwt spanning op in plaats van ze te verklappen',
    items: [
      'De kaartjes met het resultaat en de uitslag boven het rapport zijn weg: die verklapten alles vóór de cijfers konden rollen',
      'De animatie is een wedstrijdtijdlijn: elk doelpunt van beide kanten verschijnt op het moment waarop het viel, met de tussenstand erbij',
      'Pas op het einde klinkt het affluiten met de uitslag — alles binnen een seconde of drie, klikken slaat over',
      'Daarna rollen de cijfers binnen, en pas dan verschijnen de nieuwsflitsen regel per regel',
      'De minuten van de tegenstander komen uit een eigen toevalsbron: een opgeslagen spel speelt exact hetzelfde verder',
    ],
  },
  {
    version: '0.53.2',
    date: '2026-09-24',
    title: 'Het sponsorbedrag blijft binnen zijn vak',
    items: [
      'Het invoerveld op de prijskaart stak 25 pixels uit onder de plusknop: de cijfers plakten tegen de "+"',
      'Het veld rekende zijn breedte op het hele witte vak, terwijl het euroteken daar ook al in staat',
      'Nu krimpt het veld netjes mee: het bedrag staat gecentreerd tussen het euroteken en de knoppen',
    ],
  },
  {
    version: '0.53.1',
    date: '2026-09-24',
    title: 'Het spel zegt zelf wanneer er een nieuwe versie klaarstaat',
    items: [
      'Een open tabblad bleef stil een oude versie draaien, ook dagen na een update — de voettekst zei 0.50.0 terwijl de server al verder stond',
      'Het spel kijkt nu elke vijf minuten (en zodra je naar het tabblad terugkeert) naar /api/version',
      'Staat er een nieuwere versie, dan verschijnt bovenaan een banner met een ververs-knop; je spel is dan al opgeslagen',
      'Eén keer nog zelf hard verversen: tabbladen die nu nog een oudere versie draaien, hebben deze banner zelf nog niet',
    ],
  },
  {
    version: '0.53.0',
    date: '2026-09-24',
    title: 'Personeel en Sponsors: klikken om te filteren, half zoveel scrollen',
    items: [
      'Personeel: "wie heb je" en "wie kun je halen" staan naast elkaar — dat is één gedachte',
      'Klik op een functie en de kandidatenlijst filtert op die rol; nog eens klikken of het kruisje haalt de filter weg',
      'Zonder filter zie je de beste kandidaat per functie; met filter de volledige lichting',
      'De takenlijst (delegeren, een andere denkbui) staat eronder over de volle breedte',
      'Sponsors: klik op een tegel van je prijskaart en je sponsors én contacten filteren op die plaats, met dezelfde chip',
      'Gemeten: het personeelsscherm ging van 4.778 naar 2.878 pixels, met filter 1.980',
    ],
  },
  {
    version: '0.52.1',
    date: '2026-09-24',
    title: 'De kopbalk verklapt de week niet meer',
    items: [
      'Je saldo (en je klassement) in de kopbalk sprongen al naar de nieuwe stand zodra je op "Volgende week" klikte, nog vóór het weekverslag in beeld was',
      'De kopbalk toont nu de stand van vóór de week zolang de animatie of het verslag openstaat, en loopt pas bij wanneer jij het verslag sluit',
    ],
  },
  {
    version: '0.52.0',
    date: '2026-09-24',
    title: 'Je ziet vooraf wat vrij is',
    items: [
      'Sponsortegels zeggen het antwoord in plaats van de rekensom: "nog 6 vrij", "vol" of "op slot"',
      'Bij elke personeelskandidaat staat vóór je klikt of zijn functie vrij is, bezet (door wie) of nog op slot',
      'Een bezette functie heeft een eerlijke knop: "Vervang X" — opzegvergoeding plus tekengeld in één beslissing',
      'De taken van wie vertrekt, gaan mee naar zijn opvolger',
      'De melding "je hebt al iemand in die functie" kun je niet meer tegenkomen: de knop bestaat alleen waar hij kan',
    ],
  },
  {
    version: '0.51.1',
    date: '2026-09-24',
    title: 'De sponsorbezetting staat weer in beeld',
    items: [
      'Elke sponsortegel draagt de bezetting als badge in de kop: 10/16, groen zodra de plaats vol zit',
      'De teller stond als voetnootje onder het invoerveld en werd daar door niemand gezien',
      'Ook plaatsen die nog op slot staan tonen hun aantal',
      'Het stippellijntje dat uitleg aankondigt, deed het op deze tegels niet meer (dubbel class-attribuut) — hersteld',
    ],
  },
  {
    version: '0.51.0',
    date: '2026-09-24',
    title: 'Stilstaan heeft gevolgen',
    items: [
      'Degradatie beweegt de kleedkamer, progressief: uit 2de Nationale vallen kost vooral loon, uit de Pro Liga vallen kost spelers',
      'Wie blijft, levert in richting de lat van de nieuwe reeks — de klap is nu symmetrisch met de sponsors',
      'Wie boven zijn club is uitgegroeid, wil hogerop: hij verlengt niet (tegen geen enkel loon), trekt vaker biedingen en zakt in moraal',
      'Na een geweigerde licentie zien je sterkhouders dat als een breekpunt',
      'De reeks vecht terug: blijft dezelfde club bovenaan hangen, dan verhogen rivalen hun ambitie en budget',
      'Op Contracten zie je wie hogerop wil, met de reden erbij',
    ],
  },
  {
    version: '0.50.0',
    date: '2026-09-24',
    title: 'Knoppen die de goede kant op wijzen',
    items: [
      'Parking en tribune zijn verbonden: een tribune van 2.000 met een dorpsparking raakt nooit vol, en een volgelopen parking kost sfeer',
      'Uitverkocht is zichtbaar: je leest hoeveel volk er niet binnen geraakte en waarom',
      'Zuinig onderhoud raakt nu ook je sponsors en het blessurerisico — dingen die niet achter een volle tribune verstopt zitten',
      'De reeksnorm voor supporters is een plafond dat je verdient met resultaten en acties, geen roltrap',
      'Een scout zonder transferbudget zegt het je voortaan zelf',
      'De ongebruikte defect-kansfunctie is opgeruimd: één waarheid over het risico van zuinig onderhoud',
    ],
  },
  {
    version: '0.49.0',
    date: '2026-09-24',
    title: 'Inflatie geldt voor iedereen',
    items: [
      'Sponsorbedragen, spelerslonen, staflonen, tv-rechten, premies en subsidies volgen voortaan het prijspeil',
      'De doorlichting vond dat de grootste inkomstenpost én de grootste kostenpost als enige buiten de inflatie stonden',
      'Ticket-, kantine- en winkelprijzen blijven vraaggestuurd: dat zijn prijzen die jij zet, geen contracten',
      'Aan het begin van een carrière (inflatie 1) verandert er niets',
    ],
  },
  {
    version: '0.48.0',
    date: '2026-09-24',
    title: 'De bond en je sponsors reageren op stijgen en zakken',
    items: [
      'Zonder licentie voor de hogere reeks gaat een promotie niet door: je blijft, mét de eer en de premie als je kampioen werd',
      'Wie op een promotieplaats staat zonder licentie, wordt in week 30 en 41 gewaarschuwd met wat er precies ontbreekt',
      'De jaarlijkse audit en de promotieweigering rekenen met exact dezelfde lijst tekortkomingen',
      'Bij degradatie herzien sponsors hun bijdrage naar het prijspeil van de nieuwe reeks',
      'Wie voor meerdere seizoenen tekende, betaalt gewoon door — een lang contract is eindelijk ergens goed voor',
    ],
  },
  {
    version: '0.47.0',
    date: '2026-09-24',
    title: 'Een zaal heeft muren',
    items: [
      'De opbrengst van een evenement is gasten × wat een gast uitgeeft; de gasten zijn begrensd door je zaal, je tribune of je aanhang',
      'Alleen het bedrag per gast stijgt met je niveau (prestige ×1 in 3de Nationale tot ×3,1 in de Pro Liga) en het prijspeil',
      'De sponsorgebonden evenementen hangen aan het aantal bedrijven aan tafel, niet meer aan je hele sponsorportefeuille',
      'De businessclub-lunch kost €4.000 in plaats van €6.000, en brengt geen €178.000 meer op',
      'Gemeten: dezelfde uitbestedende club zakt van €714.000 netto per seizoen naar €30.000 à €136.000 naargelang haar reeks, met verhoudingen tussen 0,5 en 7,6 in plaats van tot 28,6',
    ],
  },
  {
    version: '0.46.0',
    date: '2026-09-24',
    title: 'De speler beslist mee',
    items: [
      'Een speler weegt jouw club voor hij tekent: reeks, stand, accommodatie, trainer en het niveau van de kleedkamer',
      'Tot twee punten boven jouw niveau tekent iedereen gewoon; daarboven zakt de kans, en wie weigert verdwijnt van je lijst',
      'Wie boven jouw niveau tóch tekent, laat zich de stap betalen met een hoger loon',
      'De kolom "Wil hij komen?" op Transfers toont het vooraf, met dezelfde rekensom die zijn antwoord bepaalt',
      'Een huurling kijkt alleen naar wat hij vandaag is en aanvaardt een flinke stap omlaag: hij komt om te spelen',
      'De noodaankoop onder de achttien-grens kan hier nooit op vastlopen: spelers op jouw niveau zeggen altijd ja',
    ],
  },
  {
    version: '0.45.0',
    date: '2026-09-24',
    title: 'De loonlat kent geen achterpoortjes meer',
    items: [
      'De kwaliteit van doorstromende jeugd hangt aan je jeugdwerking (coördinator, opleidingscentrum, leden), niet meer aan je reeks',
      'Een startclub in 3de Nationale merkt daar niets van; wie promoveert, krijgt zijn jeugd niet langer gratis mee omhoog',
      'Spelers die ver onder de loonlat van hun reeks betaald worden, zakken in moraal tot je bijbetaalt: loononrust',
      'Eén promotie met de gewone opslag blijft verteerbaar; twee promoties zonder heronderhandelen niet',
      'Eigen jeugd tot en met 19 jaar en huurlingen vallen buiten de loondruk',
      'Gemeten: de loonlast van een uitbestedende club stijgt van 76% naar 104% van de lat in seizoen zes, en haar sterkte-voorsprong op de reeks smelt',
    ],
  },
  {
    version: '0.44.0',
    date: '2026-09-24',
    title: 'De log is een log, geen spelfeature',
    items: [
      'Het kader "Wat je personeel besliste" is van het scherm Personeel verdwenen',
      'Er gaat ook niets meer naar de console van je browser',
      'Wat je personeel uitrekent, staat nu alleen nog in een technische log: waarden, geen verhaaltjes',
      'Per beslissing zie je de invoer, de tussenstappen en de uitkomst — efficiëntie, omkadering, elke optie met haar waarde, het optimum en wat er gezet werd',
      'Zonder VCG_LOG loggen de tests en scripts niets, en kost het de motor ook niets',
      'Het logboek zat in je opgeslagen spel; dat is eruit gehaald en oude spellen worden opgeruimd bij het laden',
    ],
  },
  {
    version: '0.43.0',
    date: '2026-09-24',
    title: 'Een echt logboek: naar een bestand en naar de terminal',
    items: [
      'Het logboek van het brein schreef alleen naar het scherm en de console — nu gaat het ook naar logs/voetbalclub.log',
      'Speel je via npm run dev, dan landen je regels in dat bestand én in de terminal waar de server draait',
      'Tests en meetscripts schrijven naar hun eigen bestand, maar alleen als je erom vraagt: VCG_LOG=debug npx mocha',
      'Vier niveaus, net als bij winston: error, warn, info en debug',
      'Waar een regel heen gaat, beslist wie het spel opstart — de motor weet er niets van, want in een browser bestaat geen bestandssysteem',
      'Een bestemming die stukgaat, legt het spel niet stil: de andere krijgen hun regel gewoon',
      'Twee regels in het logboek spraken zichzelf tegen: er stond op welke prijs je medewerker mikte, niet welke hij uiteindelijk zette',
    ],
  },
  {
    version: '0.42.0',
    date: '2026-09-24',
    title: 'Een reeks hoger spelen kost ook meer',
    items: [
      'Spelers vragen meer naarmate je hoger speelt: dezelfde man kost in de Pro Liga zes en een half keer wat hij in 3de Nationale kost',
      'Bestaande contracten blijven staan — de nieuwe lat geldt voor wie je haalt en voor wie bijtekent, dus na een promotie heb je even lucht',
      'Nieuwe wekelijkse kost: bond, scheidsrechters, afgevaardigden en verplaatsingen, en die stijgt mee met je reeks',
      'In 3de Nationale verandert er niets aan wat je betaalt: die reeks is de ijking',
      'Daarmee is een oude scheeftrekking weg: promoveren vermenigvuldigde je sponsorgeld, tv-geld en publiek terwijl je loonlast bleef staan',
      'Gemeten over zes seizoenen ging de omzet van een uitbestedende club zes keer omhoog en haar kosten maar twee keer; die kosten volgen nu mee',
      'Een club die niets doet, gaat nu rond seizoen vier failliet in plaats van seizoen zes',
    ],
  },
  {
    version: '0.41.0',
    date: '2026-09-24',
    title: 'Achttien spelers, en personeel dat elke week rondkijkt',
    items: [
      'Je kern moet minstens achttien spelers tellen: dat is de marge die je nodig hebt voor blessures en schorsingen',
      'Je kunt nooit ongewild onder die grens zakken — verkopen, uitlenen én vrijgeven kan enkel tijdens de transferperiode',
      'Daarmee is de noodoplossing van vorige versie weg: er zijn geen transfervrije spelers meer buiten de transferperiode',
      'Elke week licht je personeel eerst de club door vóór het iets beslist, en dat staat als eerste regel in het logboek',
      'Verandert er iets — een kinesist erbij, iemand haalt een ster — dan zie je in diezelfde regel wat er veranderd is en wat de beslissing daardoor werd',
      'Eén medewerker kan minder taken tegelijk aan: drie bij tachtig punten of meer, twee vanaf vijfenveertig, anders één',
      'Buiten zijn vakgebied werken kost meer: een tweede keuze haalt 75% van zijn punten, een derde 58%',
      'Wie meerdere taken doet, verliest per extra taak een tiende van zijn slagkracht',
    ],
  },
  {
    version: '0.40.0',
    date: '2026-09-24',
    title: 'Wat je personeel nodig heeft, en waarom het doet wat het doet',
    items: [
      'De efficiëntie van een medewerker hangt nu ook af van wat je club om hem heen heeft: collega\'s en accommodatie',
      'Een trainer van vijf sterren zonder kinesist, verzorger of recuperatieruimte haalt 53%; met dat alles erbij 85%',
      'Dat geldt voor elf taken: je kantine vraagt vrijwilligers en een deftige toog, je scout vraagt een opleidingscentrum, je analist vraagt wifi',
      'Zonder ondersteuning val je terug op 62% van wat je sterren toelaten — nooit lager, maar het scheelt',
      'Bij elke taak staat wat er ontbreekt en wat je eraan kunt doen',
      'Nieuw logboek: wat je personeel uitrekende vóór het iets deed, met de stappen erbij, op het scherm Personeel',
      'Verandert er iets aan je club, dan verandert hun keuze mee — en dat staat er als wijziging bij: "3 → 4 trainingen"',
      'De getallen in dat logboek komen uit dezelfde functies die daarna ook echt het werk doen',
      'Live meekijken kan met vcgDebug = true in de console van je browser',
      'Gas terugnemen bij een uitgeputte groep staat los van zijn efficiëntie: dat ziet ook een slecht omkaderde trainer',
    ],
  },
  {
    version: '0.39.0',
    date: '2026-09-24',
    title: 'Sterren bepalen wat je personeel voor je uithaalt',
    items: [
      'Personeel hébben ontgrendelt het delegeren; hoe goed het loopt, hangt nu aan één duidelijke schaal',
      'Eén ster haalt 50% van wat er uit een taak te halen valt, twee 59%, drie 68%, vier 76% en vijf 85%',
      'Die laatste 15% haalt niemand: er bestaat een wiskundig beste keuze, en die is er alleen voor jou',
      'De kantine, de ticketprijs en het trainingsschema werken nu allemaal op die schaal, gemeten tegen wat een perfecte beslissing zou opleveren',
      'Gemeten aan de toog: €3,16 per bezoeker bij één ster, €4,02 bij vijf',
      'Opleiden gaat per ster en wordt telkens fors duurder: €1.550, €3.400, €7.450 en €16.400, met 7 tot 16 weken waarin hij op 60% werkt',
      'De stap naar vier sterren wordt pas aangeboden vanaf 2de nationale, die naar vijf vanaf 1ste nationale',
      'Eén opleiding brengt hem ook echt een ster hoger, in plaats van een vage plus die niets veranderde',
      'Op het personeelsscherm staat bij elke taak hoeveel procent die medewerker eruit haalt',
    ],
  },
  {
    version: '0.38.0',
    date: '2026-09-24',
    title: 'Je personeel denkt na, en je kern heeft een ondergrens',
    items: [
      'Harde ondergrens: zak je onder de zestien spelers, dan gaat de week niet verder tot je er zelf bij haalt',
      'Je kunt daardoor nooit muurvast komen te zitten: bij een te kleine kern mag je ook buiten de transferperiode transfervrije spelers halen, en er meldt zich altijd iemand',
      'Het bestuur vult je kern niet langer zelf aan — die beslissing hoort bij jou',
      'De kantineverantwoordelijke zoekt nu echt de prijs die het meeste opbrengt, per artikel, met het vraagmodel van het spel',
      'Gemeten: een zwakke kracht haalt €3,21 per bezoeker, een topper €3,94 — en hij zet bier duurder en koffie goedkoper',
      'De trainer kijkt naar wat je club aan vermoeidheid kan wegwerken: met kine, verzorger en recuperatieruimte traint hij vijf keer, zonder drie keer',
      'Bij een uitgeputte groep neemt hij gas terug en schakelt hij over op herstel',
      'Wie zijn transfers uitbesteedt, krijgt een medewerker die de kern zelf op peil houdt in plaats van alleen per linie te versterken',
      'Gemeten: alles uitbesteden aan de staf die je al hebt eindigt in 3 tot 12 van de 12 partijen in een faillissement — autopilot is niet langer gratis',
      'Een sterspeler draagt nu een sterretje bij zijn naam, in je kern én op het veld',
    ],
  },
  {
    version: '0.37.0',
    date: '2026-09-24',
    title: 'Niets doen loopt nu altijd slecht af',
    items: [
      'Een club die niets deed, kromp zichzelf uit de problemen: contracten liepen af, spelers vertrokken gratis en de loonlast zakte mee van €214.000 naar €132.000',
      'Het bestuur vult je kern nu aan zodra ze te klein wordt om een ploeg op te stellen — met tekengeld en een loon dat jij niet onderhandeld hebt',
      'Ook je jeugd loopt leeg bij een club waar niets gebeurt: het lidgeld groeide vroeger vanzelf door terwijl je stilzat',
      'Gemeten: zes seizoenen lang niets beslissen eindigt nu in alle zes de startcombinaties in 20 van de 20 partijen failliet',
      'Je werk aan je ploeg weegt zwaarder: chemie, trainer, moraal, vorm, scherpte, rollen en spelplan tellen voor 70% in plaats van 55%',
      'Gemeten over 24 seizoenen: wie zijn ploeg opvolgt eindigt gemiddeld 6e met top vijf in bijna de helft van de seizoenen; wie alleen opstelt blijft rond de 9e plaats',
      'De balanstest speelde maar drie seizoenen en verborg daarmee dat die clubs gewoon in seizoen vier of vijf omvielen; ze speelt er nu zes',
    ],
  },
  {
    version: '0.36.0',
    date: '2026-09-24',
    title: 'De man waar ze voor komen kijken',
    items: [
      'Nieuw: sterspelers. Iemand die 20% boven zijn positiegenoten uitsteekt, is dé man van je ploeg',
      'Die 20% is nagemeten: het levert 1,02 sterspeler per kern op. Op 15% heeft elke ploeg er twee en betekent het niets; op 25% kom je er bijna nooit een tegen',
      'Hij trekt volk naar het veld — dat loopt door in je kantine en je clubwinkel — en maakt een sponsorplaats aantrekkelijker',
      'Gemeten: een gewone ster is goed voor 4% meer publiek, een echte uitschieter voor 9%',
      'Een tweede ster telt half mee en een derde een kwart, zodat een kern vol uitschieters je publiek niet verdubbelt',
      'Wie sterspeler wordt of het niet meer is, komt in het nieuws, met hoeveel hij boven de rest uitsteekt',
      'Hij staat op je bureau met wat hij opbrengt, en draagt een eigen kaartje op zijn spelerskaart',
      'Ook andere clubs halen sterspelers binnen: een ambitieuze club in je reeks tast soms diep in de buidel, en dat hoor je',
      'Een uitgeleende speler telt niet mee: hij speelt hier niet, dus hij trekt hier geen volk',
    ],
  },
  {
    version: '0.35.1',
    date: '2026-09-24',
    title: 'Een laag eruit die hier niet thuishoorde',
    items: [
      'In 0.35.0 bepaalde de gastclub hoeveel een uitgeleende speler groeide: hun trainer, hun jeugdwerking, of hij er wel in de ploeg paste',
      'Dat werkte, maar het hoort niet in dit spel: je bent eigenaar van een club, geen jeugdcoördinator die per speler een leertraject uitstippelt',
      'Een uitgeleende speler speelt nu gewoon elke week en ontwikkelt zich verder, zonder dat jij ergens iets over moet uitrekenen',
      'Wat blijft: hij gaat naar een echte club uit de wereld, je ziet onderweg hoeveel hij speelde en vooruitging, en bij zijn terugkeer staat het verhaal in het nieuws',
      'Gemeten: een seizoen uitgeleend levert +5,5 op, een seizoen op jouw bank +2,5 en een seizoen in je basiself +6,0',
    ],
  },
  {
    version: '0.35.0',
    date: '2026-09-24',
    title: 'Een uitgeleende speler speelt ergens echt',
    items: [
      'Je uitgeleende speler ging naar een willekeurige naam uit je eigen reeks, en die club deed verder niets met hem',
      'Hij komt nu terecht bij een echte club uit de wereld: eentje die meedoet, promoveert en degradeert',
      'Hij speelt daar elke week en komt een stuk sterker terug dan wanneer hij bij jou op de bank was blijven zitten',
      'Je ziet nu wat een uitleenbeurt doet: hoeveel wedstrijden hij speelde en hoeveel hij erop vooruitging, terwijl hij weg is',
      'En bij zijn terugkeer staat er een bericht met het verhaal in plaats van alleen zijn naam',
    ],
  },
  {
    version: '0.34.0',
    date: '2026-09-23',
    title: 'Een huurspeler die je wil houden',
    items: [
      'Nieuw bij Ploeg › Transfers: vraag de eigenaar of je huurspeler nog een seizoen mag blijven, of breng een bod uit om hem te kopen',
      'Jij vult het bedrag in, zij beslissen — en je ziet meteen hoe groot de kans is dat ze ja zeggen',
      'Die kans beweegt mee terwijl je aan het bedrag draait, en het is exact de rekensom die een week later het antwoord maakt',
      'Zij kijken naar hoeveel hij bij jou speelde, hoeveel hij erop vooruitging en wat je biedt',
      'Speelde hij veel, dan verlengen ze graag maar verkopen ze hem duur; zat hij op de bank, dan is het net omgekeerd',
      'Een fooi nemen ze niet in behandeling, en zeggen ze nee, dan kun je het vier weken later opnieuw proberen',
      'Praten kan vanaf week 26, als het einde van het huurcontract in zicht komt',
      'Balansfout: het seizoenseinde stuurde élke huurspeler terug, ook wie je net mocht houden — die verlenging was dus een lege afspraak',
      'Elke speler houdt nu bij op welk niveau hij binnenkwam, zodat je zijn groei kunt zien',
    ],
  },
  {
    version: '0.33.1',
    date: '2026-09-23',
    title: 'Nu vergelijk je appels met appels',
    items: [
      'Het scoutingrapport toonde hun sterkte op papier naast jouw totaal mét blessures, moraal en vorm erin — twee verschillende dingen naast elkaar',
      'Er staat nu hun échte sterkte van zondag, hetzelfde getal als waarmee het spel de wedstrijd berekent, met hun papieren cijfer erbij',
      'Correctie op 0.33.0: niet vermoeidheid was de oorzaak (die factor blijft in de praktijk 1,00), maar blessures die je besten eruit halen en moraal die wegzakt',
      'De echte achterstand was 1 à 1,6 punten, niet 3 — de uitleg van vorige versie overdreef',
      'De slijtage van je tegenstanders hangt nu aan één constante (WEAR_PEAK), bewust ruimer gezet dan een strikte gelijkstand: dat is jouw voordeel',
      'Dat is meteen de knop waar de moeilijkheidsinstelling later aan hoort te draaien: lager voor zwaarder, hoger voor makkelijker',
    ],
  },
  {
    version: '0.33.0',
    date: '2026-09-23',
    title: 'Je zakte weg omdat alleen jouw ploeg moe werd',
    items: [
      'Balansfout: alleen jouw ploeg had blessures, schorsingen, vorm en moraal — je tegenstanders waren het hele seizoen één vast getal',
      'Gemeten: met een kern op het reeksgemiddelde stond je rond speeldag 10 zo\'n 1,6 punt onder dat gemiddelde, zonder dat je iets fout deed',
      'Daardoor eindigde je met een gemiddelde ploeg standaard rond de tiende plaats van zestien',
      'Alle ploegen dragen nu hetzelfde seizoen: het loopt op tot de winterstop, de rust haalt er een stuk uit, en in de terugronde loopt het weer op',
      'De ene club heeft daarbij meer pech dan de andere, maar gemiddeld even veel',
      'Beheer weegt zwaarder mee: chemie, trainer, moraal, vorm, scherpte, rollen en spelplan tellen voor 55% in plaats van 45%',
      'Gemeten resultaat: wie zijn ploeg opvolgt eindigt nu gemiddeld 5e met 51 punten; wie niets doet blijft rond de 8e à 9e plaats staan',
      'Let op: passief spelen is opnieuw milder geworden — samen met de sponsorwijziging van 0.32.0 is de financiële druk fors gezakt',
    ],
  },
  {
    version: '0.32.0',
    date: '2026-09-23',
    title: 'De sponsormarkt staat niet langer op zijn kop',
    items: [
      'Er waren eenentwintig bedrijven voor de shirt- en borstplaats (samen twee plaatsen) en drie die een bord konden betalen (zestien plaatsen)',
      'De markt telt nu eenentachtig bedrijven, met de handelaars van het dorp als brede voet: zesentwintig bordklanten tegenover negen grote namen',
      'Drieëndertig nieuwe bedrijven erbij, van de frituur en de dakwerker tot de kinderopvang en de dansschool',
      'Nieuwe sectoren voor de jeugdsponsor: daar bestond tot nu geen enkel bedrijf voor',
      'Om de twee weken melden zich twee tot vier nieuwe contacten, met een bericht erover',
      'Handelaars die lang niets horen verliezen hun interesse en verdwijnen, zodat je lijst echt draait in plaats van stil te staan',
      'Een bedrijf waarmee een gesprek loopt, kan nooit van je lijst vallen voor je zijn antwoord hebt',
      'De sponsorbedragen gingen ongeveer 28% omhoog: sponsoring is nu 45% van je inkomsten in plaats van 38%, zoals bij een echte club in deze reeksen',
      'Je begint met een echte bordenrij en een gevarieerde mix, in plaats van met negentien borden op zestien plaatsen',
      'Balansfout: door het hogere startbedrag maakte het spel meer borden dan er plaatsen zijn',
      'Wereldfout: doekte een club op nadat alle clubnamen op waren, dan bleef die reeks voorgoed met één ploeg te weinig spelen',
      'Wereldfout: een gat in een reeks werd opgevuld bij een buur die zelf precies vol zat, waardoor het gat alleen maar heen en weer verhuisde',
      'Let op: passief spelen is door de hogere sponsorinkomsten duidelijk minder dodelijk geworden',
    ],
  },
  {
    version: '0.31.1',
    date: '2026-09-23',
    title: 'Je ploegsterkte staat in een eigen kader',
    items: [
      'Ploegsterkte, aanval en verdediging stonden als een dunne regel tussen de formatiekiezer en het veld, en lazen als een bijschrift',
      'Ze staan nu in een eigen kader met een titel, en het totaal is het grootste cijfer van het scherm',
      'De sterkte van een gemiddelde tegenstander in je reeks staat er meteen bij, in plaats van alleen in de uitleg',
    ],
  },
  {
    version: '0.31.0',
    date: '2026-09-23',
    title: 'Jij hangt de prijskaart aan de muur',
    items: [
      'Je zet nu zelf wat elke sponsorplaats per week kost: €80 voor een bord als je dat wil',
      'Bedrijven bieden geen bedrag meer aan, ze zeggen ja of nee op jouw prijs',
      'Bij elk bedrag staat meteen wat de bedrijven in de streek ervan vinden, van scherp tot onbetaalbaar',
      'In de contactenlijst staat per bedrijf de echte kans dat het ja zegt op jouw prijs, en welke plaats het zou krijgen',
      'Hoe liever bedrijven bij je club horen, hoe minder ze afhaken als je meer vraagt: reputatie, sfeer, populariteit, reeks en je commercieel medewerker bepalen hoeveel ruimte je hebt',
      'Een dorpsclub kan niets boven het gangbare bedrag vragen; een club met een naam ongeveer 75% meer',
      'Bovenaan je prijskaart staat in één zin hoeveel ruimte jouw club heeft',
      'Verlengingen en de voorstellen na een promotie gaan ook tegen jouw prijskaart, niet meer tegen een eigen bedrag',
      'Doe je niets, dan volgt elke plaats gewoon de gangbare prijs en verandert er niets aan je spel',
    ],
  },
  {
    version: '0.30.0',
    date: '2026-09-23',
    title: 'Een sterkere club mag meer vragen voor haar jeugd',
    items: [
      'De prijsgevoeligheid van het lidgeld was voor elke club dezelfde; nu hangt de helling af van hoe sterk je club staat',
      'Reputatie, opleidingscentrum, jeugdcoördinator, hoe de ploeg draait en je reeks bepalen samen je aantrekkingskracht',
      'Een dorpsclub met een slechte naam kan niet meer vragen dan de buren; een topclub bijna het dubbele',
      'Bij dezelfde prijsverhoging verliest een sterke club duidelijk minder leden dan een zwakke',
      'Een jeugdcoördinator verhoogt nu ook je plafond: +1 ploeg vanaf vaardigheid 45, +2 vanaf 75',
      'De trekkracht en het aantal ploegen dat je aankan staan op het scherm, met wat eraan bijdraagt',
      'De trekkracht is begrensd, zodat ook een topclub niet eindeloos kan blijven verhogen',
    ],
  },
  {
    version: '0.29.0',
    date: '2026-09-23',
    title: 'Je ploegsterkte beweegt mee terwijl je wisselt',
    items: [
      'Op het veld staat nu per linie wat die waard is, plus je totaal, aanval en verdediging erboven',
      'Wissel je iemand, dan zie je die cijfers meteen bewegen — daar hoef je niet meer voor naar beneden te scrollen',
      'Terwijl je wisselt, toont elke kandidaat wat hij met je ploegsterkte doet: +0,4 of −1,3',
      'Abonnementen: abonnees komen nu echt trouwer bij slecht weer. De oude regel beloofde dat maar sloeg nooit aan',
      'Vierhonderd abonnees maken van een stormwedstrijd 289 toeschouwers er 378 — en die drinken allemaal iets',
      'Komt een abonnee niet opdagen en zit de tribune vol, dan gaat zijn plaats naar iemand aan de kassa',
      'Weekrapport: de uitslag stond er drie keer en het weekmoment twee keer. Wat een eigen blok heeft, staat niet meer in het nieuws eronder',
      'Het aantal toeschouwers stond bovenaan als kaartje en nog eens bij de wedstrijd',
      'De knop "Sluiten" deed exact hetzelfde als "Naar je bureau". Sluiten laat je nu staan waar je was',
      'Overal "tegen" in plaats van "vs", en de taaltest bewaakt dat voortaan',
    ],
  },
  {
    version: '0.28.0',
    date: '2026-09-23',
    title: 'Het lidgeld had een vluchtstrook',
    items: [
      'Balansfout: boven ongeveer €510 zakte het ledenaantal niet meer, dus elke verhoging leverde daarboven gewoon meer op',
      'Je kon doorschuiven tot honderd leden aan het maximum — de hoogste opbrengst van de hele reeks bij het minste werk',
      'Ouders die het te duur vinden, haken nu exponentieel af: de opbrengst heeft één top en zakt daarna echt weg',
      'Tweede laag van dezelfde fout: je bestaande leden bleven élke prijs betalen. Je houdt er nu nooit meer dan een derde meer dan de prijs draagt',
      'De inschrijvingen hebben een toevalsmarge van ongeveer 12%: de tabel is een prognose, geen afspraak',
      'Het gangbare lidgeld groeit mee met je reeks en met de inflatie — een profclub vraagt meer dan een dorpsclub',
      'Daardoor ligt het maximum niet meer vast op €800 maar op vier keer het gangbare bedrag: tot €1.750 in de Pro Liga',
      'De tabel duidt nu twee toppen aan: de prijs die volgend seizoen het meeste opbrengt, en die op termijn',
      'Je jeugdcoördinator mikt voortaan op de lange termijn in plaats van op één goed jaar',
      'De schuifbalk liep dwars door de tekst "wordt meteen toegepast" heen',
    ],
  },
  {
    version: '0.27.0',
    date: '2026-09-23',
    title: 'Sorteren werkt weer, en het weekrapport heeft een volgorde',
    items: [
      'Bug: sorteren op tevredenheid gaf een willekeurige volgorde — een kommagetal als 60,34 werd gelezen als 6.034.210.371',
      'Bug: een kolom met getallen én een streepje wisselde halverwege van vergelijkingsmethode, waardoor de volgorde onvoorspelbaar werd',
      'Bug: sorteren op naam nam ook de kaartjes achter de naam mee, dus A–Z liep door elkaar',
      'Lege cellen staan nu altijd onderaan, en gelijke waarden houden hun oorspronkelijke volgorde',
      'Elke sorteerbare kolom in twaalf tabellen is nagelopen',
      'Het weekrapport heeft een leesvolgorde gekregen: eerst de uitslag, dan de wedstrijd, dan het geld, dan de rest',
      'Het geldoverzicht splitst nu in wat binnenkwam en wat uitging, elk met een eigen subtotaal',
      'De knop "Naar je bureau" en de kop blijven staan: na een drukke week stond die knop buiten beeld',
      'Lange lijsten in het rapport klappen dicht zodra ze meer dan vijf regels tellen',
      'De tooltip wijkt uit naar links als er een venster openstaat, zodat hij de knop niet meer afdekt',
    ],
  },
  {
    version: '0.26.0',
    date: '2026-09-23',
    title: 'Taal die je begrijpt zonder voorkennis',
    items: [
      'Nieuw scherm Geld › Tickets en lidgeld: je ticketprijs, je abonnementen en het lidgeld van de jeugd staan nu bij elkaar',
      'Die drie stonden verspreid — twee ergens op Financiën, één onderaan Clubinfo — en waren daardoor moeilijk terug te vinden',
      'De kopbalk krimpt niet meer als je scrolt: wat je bovenaan ziet, zie je overal',
      'Getalvelden waren te smal voor hun eigen inhoud: "€230" werd "23(". Ze meten zich nu naar het grootste getal dat erin past',
      'Taalronde over het hele spel, gericht op spelers vanaf een jaar of tien zonder het kinderachtig te maken',
      'De kolomkoppen van je kern stonden vol afkortingen: "Kwal/Pot", "Techn/Fys", "Moe", "Loon/w". Ze staan nu voluit, met uitleg',
      'De codes "S2" en "W17" zijn overal vervangen door "nog 2 seizoenen" en "week 17"',
      '"Niet genoeg geld." zegt nu hoeveel iets kost, hoeveel je hebt, hoeveel je tekortkomt en waar je een lening aanvraagt',
      'Knoppen zeggen wat ze doen: "Starten" werd "Bouwen" of "Vrijwilligers zoeken", "Ontbind" werd "Wegsturen", "Voorstellen" werd "Dit bod doen"',
      'Het scherm "Wat beïnvloedt wat" las als een rekenblad: formules als "× prijsgevoeligheid tot de macht 1,2" zijn vervangen door gewone zinnen',
      'Vormen als "speler(s)" en "wedstrijd(en)" zijn weg, net als "±", "vs" en "incl."',
      'Vier tooltips die drie of vier dingen tegelijk uitlegden zijn gesplitst: het kernidee blijft in de tooltip, de rest staat op het scherm',
      'Een test bewaakt deze regels, zodat afkortingen en formuliertaal niet terugsluipen',
    ],
  },
  {
    version: '0.25.0',
    date: '2026-09-23',
    title: 'Je plaats in het klassement staat altijd in beeld',
    items: [
      'De kopbalk toont nu week, speeldag, klassement, volgende match en saldo op één lijn, elk met een kopje erboven',
      'Je plaats in het klassement kleurt groen op een promotieplaats en rood in de degradatiezone',
      'Die kleur komt uit dezelfde functie waarmee het seizoen wordt afgerekend, dus wat rood staat degradeert ook echt',
      'Elk cijfer in de kopbalk is een knop naar het scherm waar het vandaan komt',
      'Bug: op Ploeg › Strategie gingen training en wedstrijdtactiek mee op slot als je alleen je opstelling had uitbesteed',
      'Het slotje staat nu op het blok waar het over gaat, en noemt de persoon die beslist in plaats van een taak die niet bestond',
      'Alle drie de taken — training, opstelling en wedstrijdtactiek — staan nu in de kiezer bovenaan dat scherm',
      'De kalender stond dubbel: het wedstrijdenoverzicht bij Competitie heet nu "Jouw wedstrijden"',
      'De echte agenda met alle 52 weken verhuisde naar Bureau › Agenda',
      'Sponsors: de twee tabellen krijgen de volle breedte in plaats van een vak van 250 pixels waarin elke cel over drie regels brak',
      'Doelen: de keuze van je langetermijndoel staat als raster over de volle breedte in plaats van in een smalle kolom',
      'Financiën: vaste kolommen in plaats van een raster dat zichzelf vulde en de halve pagina wit liet',
    ],
  },
  {
    version: '0.24.0',
    date: '2026-09-23',
    title: 'De kopbalk blijft staan, en een spelerskaart legt zichzelf uit',
    items: [
      'De kopbalk blijft nu boven in beeld staan, ook als je scrolt: je clublogo, je clubnaam en je saldo zijn altijd bereikbaar',
      'Zodra je scrolt krimpt hij: het logo wordt kleiner en de datumregel gaat weg, zodat hij geen kwart van je scherm opeet',
      'Kopbalk, menubalk en subbalk plakken voortaan als één blok, dus er kan geen band meer overblijven waar een tabel doorheen schuift',
      'Je saldo stond twee keer op het scherm; het staat nu alleen nog in de kopbalk',
      'De tooltip rechtsonder schuift boven de speelbalk, zodat hij de knop "Volgende week" niet meer afdekt',
      'Hetzelfde voor de meldingen onderaan: die lagen half achter de speelbalk',
      'Op een spelerskaart staat "30 jaar · leider · kernspeler" niet meer als losse regel: het zijn drie kaartjes met een icoontje, en bij elk staat wat het betekent',
      'Elk karakter vertelt nu wat het doet — een lastpak pakt 2,5× zoveel kaarten, een harde werker groeit 1,3× zo snel',
      'De cryptische "S2" is weg: er staat "nog 2 seizoenen" of "laatste seizoen"',
      'Loon en contract staan als twee benoemde feiten onder elkaar in plaats van op één regel achter elkaar',
      'De knoppen op een kaart zien er nu uit als knoppen, met een randje en een eigen vlak',
      'Het menu "Dashboard" heet voortaan "Bureau"',
      'Op de clubpagina duwde een brede tabel in een smalle kolom de hele pagina opzij; die tabellen schuiven nu binnen hun eigen kader',
    ],
  },
  {
    version: '0.23.2',
    date: '2026-09-23',
    title: 'Clubkleuren met wit erin verdwenen tegen een witte kaart',
    items: [
      'Een clubkleur die wit of bijna wit is, liep naadloos over in de witte kopbalk',
      'De kleurenband bovenaan gebruikt nu bijgetrokken kleuren, zodat je allebei de helften ziet',
      'Elk clublogo heeft een omtrek gekregen, zodat een witte helft niet meer wegvalt',
      'De initialen op het logo kiezen hun kleur op basis van de twee helften samen, met een randje in de tegenkleur',
      'Daardoor blijven ze leesbaar op elke combinatie, ook op blauw-wit of geel-zwart',
    ],
  },
  {
    version: '0.23.1',
    date: '2026-09-23',
    title: 'Je kern als kaarten, of als tabel',
    items: [
      'Nieuwe kaartweergave van je kern: per linie, met één stip voor de toestand en de kwaliteit groot',
      'Elke kaart toont alleen wat er nu toe doet — vorm, vermoeidheid, een contract dat afloopt, een groeispurt',
      'De tabel van zeventien kolommen blijft bestaan voor wie wil sorteren en vergelijken; je schakelt met één klik',
      'Je keuze blijft bewaard, ook als je het spel sluit',
    ],
  },
  {
    version: '0.23.0',
    date: '2026-09-23',
    title: 'Overal zien wat iets oplevert',
    items: [
      'Elk bouwproject toont nu wat het je oplevert: toeschouwers, kantine, jeugdleden — én wat het aan vaste kosten kost',
      'De tribuneschuif rekent live mee: sleep en je ziet meteen hoeveel plaatsen en hoeveel onderhoud erbij komt',
      'Op de transfermarkt staat per speler wat hij aan je beste elf toevoegt; vaak is dat niets, en dan betaal je voor de bank',
      'Het weekrapport opent met kaartjes: resultaat, uitslag, publiek, records en mijlpalen in één oogopslag',
      'Spelers hebben één gekleurde stip voor hun toestand in plaats van vijf iconen door elkaar',
      'De speelknoppen en je saldo staan nu in een vaste balk onderaan, altijd in beeld, met hoeveel er op je wacht',
      'De tabelkop scrolde door de tabel heen; de menubalken blijven nu netjes bovenaan en de kopbalk schuift gewoon weg',
      'Feitenlijstjes braken hun waarden over drie regels af; die hebben nu ruimte en een rustige lijn ertussen',
    ],
  },
  {
    version: '0.22.1',
    date: '2026-09-23',
    title: 'De handleiding wees nog naar de oude menu\'s',
    items: [
      'Na de herindeling verwees de handleiding nog naar "Club › Financiën" en "Club › Cijfers", die daar niet meer staan',
      'Nieuw: "Waar vind ik wat?" zet per menu op een rij wat je er terugvindt',
      'Ook de taakbeschrijvingen wijzen nu naar het juiste scherm (Geld › Sponsors in plaats van "tab Sponsors")',
      'Op Financiën staan de investeerderskaart en de abonnementen naast elkaar in plaats van elk over de volle breedte',
    ],
  },
  {
    version: '0.22.0',
    date: '2026-09-23',
    title: 'Je eigen kleuren, en cijfers die zeggen wat ze doen',
    items: [
      'Bij een nieuw spel kies je een kleurenschema; die kleuren lopen door de hele app, van je logo tot je knoppen',
      'Elk schema is doorgerekend op leesbaarheid: geel wordt oker waar tekst nodig is, de echte clubkleur blijft op je logo en de band',
      'Bestaande spellen krijgen automatisch het schema dat het dichtst bij hun oude clubkleuren ligt',
      'De kopbalk is opnieuw gemaakt: logo en clubnaam bijna twee keer zo groot, met je clubkleuren als band erboven',
      'De seizoensbalk verhuisde van de kopbalk naar de kalender, waar ze ruimte heeft en waar je ze zoekt',
      'Nieuw op Personeel: per persoon staat er nu in kaartjes wát hij oplevert — teamsterkte, blessurekans, toeschouwers, euro\'s',
      'Bij kandidaten is dat het verschil met wie je nu hebt, doorgerekend met dezelfde formules waarmee het spel rekent',
      'Op een breed scherm valt het dashboard zelf in twee kolommen, zodat je minder scrolt',
      'De opstelling is een veld geworden met je kern ernaast: klik wie eruit moet, klik wie erin komt',
      'Strategie staat in drie kolommen en de sponsorplaatsen als tien tegels in plaats van drie uitgerekte blokken',
      'Inklappijltjes zijn echte ronde knoppen geworden in plaats van een grijs driehoekje van zes pixels',
    ],
  },
  {
    version: '0.21.1',
    date: '2026-09-23',
    title: 'De week begint met wat er op je ligt te wachten',
    items: [
      '"Deze week" staat nu bovenaan over de volle breedte: het eerste wat je bekijkt, niet een kaartje in de zijkolom',
      'De beslissing van de week zit erin als eerste regel, met de knop erbij, in plaats van in een aparte kaart',
      'Elke regel zegt er nu bij wat er op het spel staat: waarom het dringend is, of wanneer het vervalt',
      'Rood is voor echte problemen; de gewone weekbeslissing krijgt de clubkleur zodat de rode streep iets blijft betekenen',
      'De kopbalk is herbouwd: de vijf kerncijfers die het dashboard al groot toont staan er niet meer dubbel',
      'Nieuw in de kopbalk: een seizoensbalk met de 52 weken, elke speeldag als streepje, de winterstop en de transferperiodes als band',
      'Daarmee zie je in één blik of het venster open is, hoeveel weken tot de volgende match, en wanneer de eindstand valt',
      'Op een telefoon is de kopbalk ongeveer gehalveerd, zodat je meteen bij je werklijst uitkomt',
    ],
  },
  {
    version: '0.21.0',
    date: '2026-09-23',
    title: 'Een dashboard in plaats van een spreadsheet',
    items: [
      'Het dashboard is van nul herbouwd vanuit het oogpunt van een eigenaar: links geld, posten en wedstrijd, rechts wat je aandacht vraagt',
      'Saldo, resultaat van de week en de prognose over acht weken staan nu groot bovenaan',
      'Publiek, sponsors en je clubscores tonen niet alleen een cijfer maar ook wat dat cijfer concreet doet',
      'Nieuws is naar onderaan verhuisd; je langetermijndoel en de seizoensdoelen staan nu bij Club › Doelen',
      'Nieuwe look in de hele app: geen kaderlijnen meer, meer ruimte, zwaardere cijfers en rustiger tabellen',
      'Het menu is opnieuw ingedeeld: Geld kreeg een eigen tab, en Club heeft geen tien subtabs meer',
      'Tooltips verschijnen voortaan groot en leesbaar rechtsonder in beeld in plaats van als browsertekstje bij je muis',
      'Getalvelden hebben echte min- en plusknoppen die je kunt raken, met doorlopen bij ingedrukt houden en shift voor stappen van tien',
      'Op elk taakscherm (kantine, clubwinkel, tactiek, sponsors, …) kies je nu ter plekke wie de taak doet',
      'De startlijst voor nieuwe eigenaars is een strook geworden in plaats van een half scherm',
    ],
  },
  {
    version: '0.20.1',
    date: '2026-09-23',
    title: 'Twee voordelen die in de praktijk niets deden',
    items: [
      'De vrijwilligersfactor zat vast op een hard plafond waar clubs vanaf week één al tegenaan zaten',
      'Daardoor was elke extra vrijwilliger — en dus ook de +40% van de coöperatie — letterlijk niets waard',
      'Het plafond is nu een afvlakkende curve: een extra paar handen levert altijd iets op, alleen steeds minder',
      'Een onderbemande club wordt nog even hard afgestraft als vroeger',
      'De coöperatie geeft nu echt +40% vrijwilligers en de lokale figuur +30%, zoals de tekst al beloofde',
      'De stadionnaam van de aannemer volgt nu ook je reputatie en het prijspeil, niet alleen je reeks',
      'Dat contract wordt nooit heronderhandeld, dus het wordt elk seizoen automatisch herbekeken',
    ],
  },
  {
    version: '0.20.0',
    date: '2026-09-23',
    title: 'Drie investeerders, drie verschillende spellen',
    items: [
      'De stadionnaam van de aannemer groeit mee met je reeks in plaats van vast te staan op €600/week',
      'Bij de aannemer zijn bouwwerken ook een kwart sneller klaar, en mag je drie werven tegelijk open hebben',
      'Het fonds neemt voortaan ook 20% van je prijzengeld, en daar valt niet aan te ontkomen',
      'Het fonds tekent zelf voor een stevig bod op een jonge speler; jij hoort het achteraf',
      'De promotie-eis van het fonds keert terug: de klok begint opnieuw bij elke promotie',
      'De coöperatie kan elk seizoen een ledenronde houden, die groeit met je supporters, reputatie en sfeer',
      'Bij de coöperatie tellen vrijwilligers zwaarder door: het plafond ligt daar op 1,35 in plaats van 1,15',
      'Je financiënscherm vertelt nu altijd wat jouw investeerder voor je club betekent',
    ],
  },
  {
    version: '0.19.0',
    date: '2026-09-23',
    title: 'Twee snelheden, vooruitkijken en beslissingen die blijven hangen',
    items: [
      'Nieuwe knop "Tot de volgende match": speelt de rustige weken achter elkaar en stopt zodra er iets is dat jou nodig heeft',
      'Na het doorspelen krijg je één venster met het saldo, de records, de mijlpalen en het nieuws van die weken',
      'Kasprognose op Financiën: tot acht weken vooruit, met een waarschuwing als je onder nul zou duiken',
      '"Waar kwam het vandaan": per post wat het weer, de opkomst, je prijzen en je vrijwilligers deze week uithaalden',
      'Twintig nieuwe weekmomenten, van de frietketel tot de scout achter het doel — 36 situaties in totaal',
      'Het moment "Je beste man is op" kon nooit gebeuren (het vroeg vermoeidheid boven 70); dat is rechtgezet',
      'Abonnementen: één keer per seizoen, geld ineens in kas, en daarna betalen die mensen niet meer aan de kassa',
      'Bij een nieuw sponsorcontract kies je zelf de looptijd: langer tekenen betaalt beter, maar schuift niet mee bij promotie',
    ],
  },
  {
    version: '0.18.0',
    date: '2026-09-23',
    title: 'Een levende reeks en een carrière met een boog',
    items: [
      'Elke club in elke reeks heeft nu een eigen bestuur: budget, ambitie, momentum, accommodatie en jeugdwerking',
      'Eén keer per zomer beslist elke club wat ze doet — versterken, bouwen, jeugd uitbreiden, besparen of de boeken neerleggen',
      'Wie vorig jaar investeerde, staat er dit jaar beter voor: de sterktes in je reeks zijn geen vaste getallen meer',
      'Op het competitiescherm zie je per club haar sterkte, ambitie, werking en wat ze vorige zomer besliste',
      'Je kiest één keer een langetermijndoel: acht doelen, van "naar 2de nationale" tot "hoog én gezond"',
      'Dat doel staat de hele carrière op je overzicht, met de actuele stand, en krijgt een plek in je museum zodra het lukt',
      'Vijf eigenaarsniveaus met elk één concreet voordeel: lagere rente, een derde bouwproject, meer sponsorprospecten, meer subsidie',
      'Keuzes werken door: een sponsorruzie loopt over drie stappen, een verkochte speler kom je later tegen, geldzorgen slepen aan',
      'Een ambitieuze rivaal met een sterke jeugdwerking kan je mooiste belofte wegkapen',
      'Nieuw in je museum: de clubkroniek met alles wat de moeite is om na te vertellen',
      'Onder de motorkap: weekmomenten, gebeurtenissen en nieuwsberichten zijn nu data in plaats van code',
    ],
  },
  {
    version: '0.17.2',
    date: '2026-09-23',
    title: 'Het weekmoment als venster',
    items: [
      'Het weekmoment verschijnt nu als venster zodra je het weekrapport sluit, zodat je het niet meer mist',
      'Het gevolg van je keuze staat in hetzelfde venster, niet meer als kort meldinkje onderaan',
      '"Later beslissen" sluit het venster; op je overzicht blijft een kader met een knop om alsnog te beslissen',
      'Dezelfde situatie komt minstens 12 weken niet terug (ze kwam soms elke week opnieuw)',
    ],
  },
  {
    version: '0.17.1',
    date: '2026-09-23',
    title: 'Jij beslist wie er speelt',
    items: [
      'Haal je iemand uit je basiself, dan blijft die plaats open: je trainer vult niet meer vanzelf aan',
      'Met een open plaats kun je niet naar de volgende week, met uitleg welke linie het betreft',
      'De spelerstabellen zijn in- en uitklapbaar; bank en niet-beschikbaar staan standaard dicht',
    ],
  },
  {
    version: '0.17.0',
    date: '2026-09-23',
    title: 'Basiself onder controle en evenementen voor elke reeks',
    items: [
      'Twee knopjes per speler: ★ vastzetten in de basis, 🪑 deze week op de bank houden',
      'Vastzetten in een volle linie verdringt nu de zwakste vastgezette speler in plaats van te weigeren',
      'Spelers springen meteen naar de juiste tabel en de tellers (11/11 en per linie) lopen mee',
      'Evenementen schalen mee: opbrengst met je club en de inflatie, kosten met de inflatie en +12% per reeks',
      'Vijf nieuwe evenementen die vrijkomen in hogere reeksen, van het sponsorontbijt tot een internationaal wintertornooi',
      'Het weekmoment valt beter op: het staat nu ook bij Aandacht en in de tip op de knop "Volgende week"',
    ],
  },
  {
    version: '0.16.1',
    date: '2026-09-23',
    title: 'Scherpere volumekorting op de tribune',
    items: [
      'De prijs per zitje zakt agressiever én versnelt: elke volgende honderd zitjes kosten minder dan de vorige',
      '€360 per extra zitje rond de 100 plaatsen, €210 rond de 1.000 en €80 rond de 2.000',
      'De uitklapbare prijstabel bij de tribune is weg: de schuifregelaar zegt het al',
    ],
  },
  {
    version: '0.16.0',
    date: '2026-09-23',
    title: 'Bouwen op jouw maat',
    items: [
      'Bij de tribune kies je met een schuifregelaar hoeveel plaatsen erbij komen (100 tot 2.000)',
      'Hoe groter je bestelt, hoe goedkoper per zitje, en die korting versnelt: van ±€450 bij 100 plaatsen naar ±€215 bij 2.000 (−52%)',
      'Grotere werken duren langer: 4 tot 22 weken',
      'Zonnepanelen zijn een bouwproject geworden en duren 5 weken',
      'Er mogen twee bouwprojecten tegelijk lopen',
    ],
  },
  {
    version: '0.15.0',
    date: '2026-09-23',
    title: 'Nederlandse termen',
    items: [
      'Staff heet nu Personeel, overal: de tab, de lonen, de tooltips en de taken',
      'T1, T2 en T3 staan voluit: hoofdtrainer, assistent-trainer en conditietrainer',
      'Fanshop werd Clubwinkel, webshop werd webwinkel, de merchandisingverantwoordelijke werd winkelverantwoordelijke',
      'Boekingscategorieën in het Nederlands: clubartikelen, inkoop winkel, werking winkel en lonen personeel',
      'Clubrating werd Clubscore, dashboard werd overzicht, Vacant werd Niet ingevuld, FAQ werd veelgestelde vragen',
      'Voetbaltermen blijven: balbezit, counter, pressing, derby, transfer, scout, keeper, kern, ticketprijs',
    ],
  },
  {
    version: '0.14.0',
    date: '2026-09-23',
    title: 'Sterkere reeksen, duidelijkere selectie en doelpuntenmakers',
    items: [
      'Elke reeks ligt nu duidelijk boven de vorige: de zwakste ploeg van 2de nationale is steviger dan de zwakste van 3de',
      'Als promovendus start je onderaan: net gepromoveerde clubs (ook jij) zijn zwakker, net gedegradeerde sterker',
      'Selectie opgesplitst in basiself, bank en niet-beschikbaar, met een teller per linie tegenover je formatie',
      'Na elke wedstrijd zie je wie scoorde (met minuut) en wie er begon; doelpunten staan ook in je spelerstabel',
      'Bankleningen schalen mee met je reeks, je loonmassa en de inflatie',
      'Het nieuws in het weekrapport rolt trager binnen',
    ],
  },
  {
    version: '0.13.0',
    date: '2026-09-23',
    title: 'Derby, weekmoment en clubmuseum',
    items: [
      'Elke reeks heeft nu zijn eigen clubs: dorpsploegen in provinciale, profclubs bovenaan',
      'Eén echte aartsrivaal met een derby die telt: meer volk, meer kaarten, dubbel effect op de sfeer, en een onderlinge balans die blijft',
      'Het weekmoment: elke week één concrete beslissing voor de aftrap, met meteen gevolg',
      'Clubmuseum onder Club: titels, records, mijlpalen, erelijst en de mensen die er iets van maakten',
      'Passief spelen is scherper afgestraft: een club waar weken niets beslist wordt, verliest sfeer, reputatie en sponsortevredenheid',
    ],
  },
  {
    version: '0.12.0',
    date: '2026-09-23',
    title: 'Een echte jeugdwerking van bij de start',
    items: [
      'Je club begint met jeugdploegen (U7 tot U17) én een jeugdcoördinator in dienst',
      'Elke ploeg bindt twee vrijwilligers: evenementen kunnen alleen de vrije vrijwilligers gebruiken',
      'Je accommodatie begrenst het aantal ploegen; kunstgras, verlichting en het opleidingscentrum maken plaats',
      'Te weinig begeleiding remt de instroom en brandt je vrijwilligers op',
      'Een jeugdcoördinator aanwerven vraagt 3 ploegen, de jeugdsponsor ook',
      'Elke ploeg kost werkingsgeld en verhoogt de aansluiting bij de bond',
    ],
  },
  {
    version: '0.11.0',
    date: '2026-09-23',
    title: 'De seizoensopening',
    items: [
      'Elk seizoen begint met een openingsscherm: affiche, voorbeschouwing van de pers, wat er deze zomer gebeurde en wie er uit de jeugd doorstroomt',
      'De persconferentie: spreek je ambitie uit (voeten op de grond, meedoen voor de prijzen of wij worden kampioen)',
      'Die keuze verandert meteen de stemming bij supporters, spelers en sponsors, en wordt op het einde van het seizoen afgerekend in geld en reputatie',
      'Het bestuur legt drie doelen op tafel, één per categorie van je clubscore, elk met een premie',
      'De doelen staan het hele seizoen op je overzicht met een voortgangsbalk, en de afrekening staat in het seizoensrapport',
    ],
  },
  {
    version: '0.10.3',
    date: '2026-09-23',
    title: 'Nieuws en afwachting rollen mee binnen',
    items: [
      'De nieuwsberichten en de lijst "In afwachting" verschijnen regel per regel, samen met de cijfertellers',
      'Hele regels tegelijk, geen letter-per-letter getik',
      'Staat de animatie uit bij Opslaan, of vraagt je systeem minder beweging, dan staat alles er meteen',
    ],
  },
  {
    version: '0.10.2',
    date: '2026-09-23',
    title: 'Rustiger weekanimatie en een zichtbare premie',
    items: [
      'De animatie voor het weekrapport duurt twee keer zo lang: de bal rolt trager en de drie tussentitels blijven staan',
      'De cijferrollers tellen ongeveer 20% trager op, post per post',
      'Kampioenen- en promotiepremie staan nu apart onder "premies" in plaats van tussen de meevallers',
      'De premie staat in het weekrapport, in het seizoensrapport, bij Club › Cijfers en in je clubgeschiedenis; de kalender toont vooraf wat de titel waard is',
    ],
  },
  {
    version: '0.10.1',
    date: '2026-09-23',
    title: 'Herstel van opslagbestanden',
    items: [
      'Opslagbestanden van een tussenversie misten de clubrecords, waardoor "Volgende week" niets meer deed',
      'Elk bestand wordt nu bij het laden aangevuld met alles wat het nog niet kent',
      'Gaat er toch iets mis tijdens een week, dan krijg je een melding in plaats van een knop die niets doet',
    ],
  },
  {
    version: '0.10.0',
    date: '2026-09-23',
    title: 'Promotie verandert alles: inkomsten én kosten',
    items: [
      'Kampioenen- en promotiepremie: bescheiden in de amateurreeksen, echt prijzengeld vanaf de Challenger Pro Liga',
      'Na promotie vragen spelers 14% en personeel 10% meer; na degradatie wordt er neerwaarts onderhandeld',
      'Aansluiting bij de bond en verzekeringen schalen met je reeks, de gemeentesubsidie ook',
      'De richtprijzen in de fanshop volgen het niveau van je reeks',
    ],
  },
  {
    version: '0.9.9',
    date: '2026-09-23',
    title: 'Wedstrijdpremies en sponsors na promotie',
    items: [
      '30% van de spelersvergoeding is een wedstrijdpremie: in een week zonder wedstrijd betaal je die niet',
      'Een zege kost een winstpremie van 12% aan de basiself',
      'Na promotie bieden sponsors spontaan een hoger contract aan en stijgt hun tevredenheid',
      'Na degradatie zakt de tevredenheid van je sponsors',
    ],
  },
  {
    version: '0.9.8',
    date: '2026-09-22',
    title: 'Teller post per post, jong talent en promotie in het rapport',
    items: [
      'De bedragen in het weekrapport tellen post per post op, elk met een klein accent als ze landen',
      'Jonge spelers groeien sneller (tot 19 jaar +30%, tot 21 jaar +15%) en worden minder snel moe',
      'Oudere spelers raken sneller vermoeid',
      'Het seizoensrapport toont het echte resultaat: kampioen, promotie, degradatie of behoud, met de reeks waarin je volgend seizoen speelt',
    ],
  },
  {
    version: '0.9.7',
    date: '2026-09-22',
    title: 'Spanning per week: records, reeksen en onthulling',
    items: [
      'De animatie bouwt op met drie momenten en een voortgangsbalk',
      'De uitslag springt eruit zodra het rapport opent, daarna lopen de bedragen op',
      'Clubrecords: opkomst, beste week, langste reeks en meeste supporters, met een melding als er een sneuvelt',
      'Een lopende reeks (drie zeges of vier ongeslagen) staat bij de uitslag',
    ],
  },
  {
    version: '0.9.6',
    date: '2026-09-22',
    title: 'Eerlijke fanshopmarge en een echt seizoenseinde',
    items: [
      'Fanshop: inkoop van verkochte artikelen en vaste werkingskosten staan apart, zodat je je echte marge ziet',
      'De knop toont wanneer het de laatste speeldag is of wanneer je het seizoen afsluit',
      'Seizoensrapport met eindstand, resultaten, inkomsten tegenover vorig seizoen, supporters, jeugd en mijlpalen',
    ],
  },
  {
    version: '0.9.5',
    date: '2026-09-22',
    title: 'Mijlpalen, tellers en thuisvoordeel',
    items: [
      'Geschiktheid van een staflid voor een taak staat in sterren',
      'Mijlpalen: elf momenten om naar toe te werken, met een beloning en een plek bovenaan het weekrapport',
      'De bedragen in het weekrapport tellen op als een teller',
      'Thuis spelen geeft een klein voordeel; uit spelen een klein nadeel',
      'Supporters groeien sneller als je ploeg goed draait, dus succes bouwt op zichzelf verder',
    ],
  },
  {
    version: '0.9.4',
    date: '2026-09-22',
    title: 'Bank, terugverdientijd en scherpere wedstrijden',
    items: [
      'Een kredietaanvraag gaat naar de bank: antwoord volgt een week later (een noodlening staat er wel meteen op)',
      'Zonnepanelen kosten wat bij jouw complex hoort en zijn na ongeveer drie seizoenen terugverdiend; de ploegbus idem',
      'Wedstrijden zijn scherper: staff, sfeer en vorm wegen minder door dan de kwaliteit van je spelers, en tegenstanders hebben ook een trainer',
      'De meldingen bij Aandacht zijn links naar het juiste scherm',
    ],
  },
  {
    version: '0.9.3',
    date: '2026-09-22',
    title: 'Specialisatie, menu en eerste stappen',
    items: [
      'Een staflid werkt buiten zijn vakgebied op een lager niveau en kan 1 tot 4 taken aan',
      'Hamburgermenu rechtsboven met de handleiding en het opslaan',
      'Handleiding met veelgestelde vragen',
      'Startlijst "Eerste stappen" op het overzicht voor een nieuwe eigenaar',
      'Kantineverbruik realistischer: ongeveer 2 consumpties per bezoeker in plaats van 6',
      'De ploegbus is een investering geworden en ontgrendelt pas dan de bussponsor',
    ],
  },
  {
    version: '0.9.2',
    date: '2026-09-22',
    title: 'Winterstop, kopbalk en duidelijkere boekingen',
    items: [
      'Clubscore staat naast de clubnaam in plaats van eronder',
      'Winterstop is duidelijk zichtbaar: in de kopbalk, op het overzicht en in het weekrapport',
      'Tijdens de winterstop draait de kantine op halve kracht',
      '"Concessies" heet nu "horeca concessies" in alle overzichten',
      'Wedstrijdkosten benoemen of het om een thuis- of uitwedstrijd gaat',
    ],
  },
  {
    version: '0.9.1',
    date: '2026-09-22',
    title: 'Delegeren, sponsorplaatsen en heldere ticketinkomsten',
    items: [
      'Elke taak krijgt een keuzelijst bij Staff: kies per taak wie ze doet',
      'Drie nieuwe taken: jeugdwerking (lidgeld), belasting en blessurepreventie, onderhoud en bouwprojecten',
      'Ticketinkomsten staan nu bruto in de boeken, met het aandeel van de bezoekers en de bond (8%) als aparte kost',
      'Kopbalk is klikbaar: klassement, hoofdsponsor, saldo, teamsterkte en datum brengen je naar het juiste scherm',
      'Meer soorten sponsoring: mouw, ploegbus, evenementen, schermen in de kantine en de wedstrijdbal; de sectoren zijn evenwichtiger verdeeld',
      'Een uitgeleende speler kun je gewoon een nieuw contract geven',
    ],
  },
  {
    version: '0.9.0',
    date: '2026-09-22',
    title: 'Onderhandelen, weekcijfers en scherpere balans',
    items: [
      'Transferperiode staat duidelijk open of gesloten bovenaan de tab Transfers',
      'Loononderhandelingen lopen vast als je blijft laagbieden: hij vraagt meer, verliest moraal en haakt na drie pogingen af',
      'Cijfers ook per week, met de opbrengst per bron; horeca staat nu overal tussen de inkomsten',
      'Clubscore staat in de kopbalk naast de clubnaam',
      'Je kiest je eigen clubnaam bij de start',
      'Nieuw bouwproject: scorebord (meer sfeer, bordsponsors betalen meer)',
      'Meer staf vraagt eerst de juiste infrastructuur (analist wifi, kantineverantwoordelijke een degelijke kantine, ...)',
      'Vrijwilligers op een menselijke schaal: ongeveer 12 in plaats van 28, evenementen vragen er 3 tot 14',
      'Sponsornaam en sector kloppen nu ook in oude opslagbestanden',
      'Passief spelen is duidelijk moeilijker gemaakt',
    ],
  },
  {
    version: '0.8.0',
    date: '2026-09-22',
    title: 'Kern, contracten, horeca en cijfers',
    items: [
      'Transfers: je laatste doelman blijft, elke linie houdt een reserve en je zakt nooit onder 16 spelers',
      'Contracten verlengen met een loonvoorstel dat de moraal beïnvloedt (Ploeg › Contracten)',
      'Kantineprijzen per artikel en horecaconcessies met onderhandelde marge (Club › Horeca)',
      'Cijfers per seizoen: tickets, consumpties, merchandising en leden (Club › Cijfers)',
      'Populariteit weegt op alle inkomsten; wat men voor een shirt betaalt, stijgt mee',
      'Spelersrollen: kapitein, strafschop- en hoekschopnemer',
      'Delegeren per deeltaak: training, opstelling, tactiek, spelersrollen, transfers, horeca',
      'Vaste menubalk, automatisch opslaan van invoervelden, 11/11-teller en tooltips',
      'Nieuwe infrastructuur: wifi, sanitair, parking; onderhoudsniveau en zonnepanelen',
      'Vrijwilligers komen en gaan; evenementen vragen meer volk',
      'Logboek van je beslissingen en antwoorden op de tab Overzicht',
    ],
  },
  { version: '0.7.0', date: '2026-09-22', title: 'Fanshop en leeftijdscurve', items: ['Fanshop met assortiment en prijzen', 'Vloeiende leeftijdscurve voor de evolutie van spelers'] },
  { version: '0.6.0', date: '2026-09-22', title: 'Weekrapport en kalender', items: ['Animatie en weekrapport', 'Seizoenskalender', 'Verkopen, te koop zetten, uitlenen en huren'] },
  { version: '0.5.0', date: '2026-09-21', title: 'Blessures, kaarten en herstel', items: ['Kaarten en schorsingen', 'Forfait', 'Herstelmechanisme en extra staff'] },
  { version: '0.4.0', date: '2026-09-21', title: 'Opleiding, financiën en invloeden', items: ['Opleidingen voor staff', 'Weekfinanciën', 'Tab Invloeden', 'Vermoeidheid en scouting'] },
  { version: '0.3.0', date: '2026-09-20', title: 'Strategie en jeugd', items: ['Strategietab met spelplannen', 'Lidgeld jeugd'] },
  { version: '0.2.0', date: '2026-09-20', title: 'Staff, sponsors en evenementen', items: ['Meer staff en delegeren', 'Sponsorwerving', 'Evenementen met vrijwilligers'] },
  { version: '0.1.0', date: '2026-09-19', title: 'Eerste versie', items: ['Club, investeerder, competitie, transfers en financiën'] },
];
