// Versie van het spel. Semantisch: MAJOR.MINOR.PATCH.
// Elke laag verhoogt MINOR, kleine correcties verhogen PATCH.

export const VERSION = '0.28.0';

export interface ChangeEntry {
  version: string;
  date: string;
  title: string;
  items: string[];
}

export const CHANGELOG: ChangeEntry[] = [
  {
    version: '0.28.0',
    date: '2026-09-23',
    title: 'Het lidgeld had een vluchtstrook',
    items: [
      'Balansfout: boven ongeveer €510 zakte het ledenaantal niet meer, dus elke verhoging leverde daarboven gewoon meer op',
      'Je kon doorschuiven tot honderd leden aan het maximum — de hoogste opbrengst van de hele reeks bij het minste werk',
      'Ouders die het te duur vinden, haken nu exponentieel af: de opbrengst heeft één top en zakt daarna echt weg',
      'Tweede laag van dezelfde fout: je bestaande leden bleven élke prijs betalen. Je houdt er nu nooit meer dan een derde meer dan de prijs draagt',
      'De inschrijvingen hebben een toevalsmarge van ongeveer 12%: de tabel is een prognose, geen afspraak',
      'Het gangbare lidgeld groeit mee met je reeks en met de inflatie — een profclub vraagt meer dan een dorpsclub',
      'Daardoor ligt het maximum niet meer vast op €800 maar op vier keer het gangbare bedrag: tot €1.750 in de Pro Liga',
      'De tabel duidt nu twee toppen aan: de prijs die volgend seizoen het meeste opbrengt, en die op termijn',
      'Je jeugdcoördinator mikt voortaan op de lange termijn in plaats van op één goed jaar',
      'De schuifbalk liep dwars door de tekst "wordt meteen toegepast" heen',
    ],
  },
  {
    version: '0.27.0',
    date: '2026-09-23',
    title: 'Sorteren werkt weer, en het weekrapport heeft een volgorde',
    items: [
      'Bug: sorteren op tevredenheid gaf een willekeurige volgorde — een kommagetal als 60,34 werd gelezen als 6.034.210.371',
      'Bug: een kolom met getallen én een streepje wisselde halverwege van vergelijkingsmethode, waardoor de volgorde onvoorspelbaar werd',
      'Bug: sorteren op naam nam ook de kaartjes achter de naam mee, dus A–Z liep door elkaar',
      'Lege cellen staan nu altijd onderaan, en gelijke waarden houden hun oorspronkelijke volgorde',
      'Elke sorteerbare kolom in twaalf tabellen is nagelopen',
      'Het weekrapport heeft een leesvolgorde gekregen: eerst de uitslag, dan de wedstrijd, dan het geld, dan de rest',
      'Het geldoverzicht splitst nu in wat binnenkwam en wat uitging, elk met een eigen subtotaal',
      'De knop "Naar je bureau" en de kop blijven staan: na een drukke week stond die knop buiten beeld',
      'Lange lijsten in het rapport klappen dicht zodra ze meer dan vijf regels tellen',
      'De tooltip wijkt uit naar links als er een venster openstaat, zodat hij de knop niet meer afdekt',
    ],
  },
  {
    version: '0.26.0',
    date: '2026-09-23',
    title: 'Taal die je begrijpt zonder voorkennis',
    items: [
      'Nieuw scherm Geld › Tickets en lidgeld: je ticketprijs, je abonnementen en het lidgeld van de jeugd staan nu bij elkaar',
      'Die drie stonden verspreid — twee ergens op Financiën, één onderaan Clubinfo — en waren daardoor moeilijk terug te vinden',
      'De kopbalk krimpt niet meer als je scrolt: wat je bovenaan ziet, zie je overal',
      'Getalvelden waren te smal voor hun eigen inhoud: "€230" werd "23(". Ze meten zich nu naar het grootste getal dat erin past',
      'Taalronde over het hele spel, gericht op spelers vanaf een jaar of tien zonder het kinderachtig te maken',
      'De kolomkoppen van je kern stonden vol afkortingen: "Kwal/Pot", "Techn/Fys", "Moe", "Loon/w". Ze staan nu voluit, met uitleg',
      'De codes "S2" en "W17" zijn overal vervangen door "nog 2 seizoenen" en "week 17"',
      '"Niet genoeg geld." zegt nu hoeveel iets kost, hoeveel je hebt, hoeveel je tekortkomt en waar je een lening aanvraagt',
      'Knoppen zeggen wat ze doen: "Starten" werd "Bouwen" of "Vrijwilligers zoeken", "Ontbind" werd "Wegsturen", "Voorstellen" werd "Dit bod doen"',
      'Het scherm "Wat beïnvloedt wat" las als een rekenblad: formules als "× prijsgevoeligheid tot de macht 1,2" zijn vervangen door gewone zinnen',
      'Vormen als "speler(s)" en "wedstrijd(en)" zijn weg, net als "±", "vs" en "incl."',
      'Vier tooltips die drie of vier dingen tegelijk uitlegden zijn gesplitst: het kernidee blijft in de tooltip, de rest staat op het scherm',
      'Een test bewaakt deze regels, zodat afkortingen en formuliertaal niet terugsluipen',
    ],
  },
  {
    version: '0.25.0',
    date: '2026-09-23',
    title: 'Je plaats in het klassement staat altijd in beeld',
    items: [
      'De kopbalk toont nu week, speeldag, klassement, volgende match en saldo op één lijn, elk met een kopje erboven',
      'Je plaats in het klassement kleurt groen op een promotieplaats en rood in de degradatiezone',
      'Die kleur komt uit dezelfde functie waarmee het seizoen wordt afgerekend, dus wat rood staat degradeert ook echt',
      'Elk cijfer in de kopbalk is een knop naar het scherm waar het vandaan komt',
      'Bug: op Ploeg › Strategie gingen training en wedstrijdtactiek mee op slot als je alleen je opstelling had uitbesteed',
      'Het slotje staat nu op het blok waar het over gaat, en noemt de persoon die beslist in plaats van een taak die niet bestond',
      'Alle drie de taken — training, opstelling en wedstrijdtactiek — staan nu in de kiezer bovenaan dat scherm',
      'De kalender stond dubbel: het wedstrijdenoverzicht bij Competitie heet nu "Jouw wedstrijden"',
      'De echte agenda met alle 52 weken verhuisde naar Bureau › Agenda',
      'Sponsors: de twee tabellen krijgen de volle breedte in plaats van een vak van 250 pixels waarin elke cel over drie regels brak',
      'Doelen: de keuze van je langetermijndoel staat als raster over de volle breedte in plaats van in een smalle kolom',
      'Financiën: vaste kolommen in plaats van een raster dat zichzelf vulde en de halve pagina wit liet',
    ],
  },
  {
    version: '0.24.0',
    date: '2026-09-23',
    title: 'De kopbalk blijft staan, en een spelerskaart legt zichzelf uit',
    items: [
      'De kopbalk blijft nu boven in beeld staan, ook als je scrolt: je clublogo, je clubnaam en je saldo zijn altijd bereikbaar',
      'Zodra je scrolt krimpt hij: het logo wordt kleiner en de datumregel gaat weg, zodat hij geen kwart van je scherm opeet',
      'Kopbalk, menubalk en subbalk plakken voortaan als één blok, dus er kan geen band meer overblijven waar een tabel doorheen schuift',
      'Je saldo stond twee keer op het scherm; het staat nu alleen nog in de kopbalk',
      'De tooltip rechtsonder schuift boven de speelbalk, zodat hij de knop "Volgende week" niet meer afdekt',
      'Hetzelfde voor de meldingen onderaan: die lagen half achter de speelbalk',
      'Op een spelerskaart staat "30 jaar · leider · kernspeler" niet meer als losse regel: het zijn drie kaartjes met een icoontje, en bij elk staat wat het betekent',
      'Elk karakter vertelt nu wat het doet — een lastpak pakt 2,5× zoveel kaarten, een harde werker groeit 1,3× zo snel',
      'De cryptische "S2" is weg: er staat "nog 2 seizoenen" of "laatste seizoen"',
      'Loon en contract staan als twee benoemde feiten onder elkaar in plaats van op één regel achter elkaar',
      'De knoppen op een kaart zien er nu uit als knoppen, met een randje en een eigen vlak',
      'Het menu "Dashboard" heet voortaan "Bureau"',
      'Op de clubpagina duwde een brede tabel in een smalle kolom de hele pagina opzij; die tabellen schuiven nu binnen hun eigen kader',
    ],
  },
  {
    version: '0.23.2',
    date: '2026-09-23',
    title: 'Clubkleuren met wit erin verdwenen tegen een witte kaart',
    items: [
      'Een clubkleur die wit of bijna wit is, liep naadloos over in de witte kopbalk',
      'De kleurenband bovenaan gebruikt nu bijgetrokken kleuren, zodat je allebei de helften ziet',
      'Elk clublogo heeft een omtrek gekregen, zodat een witte helft niet meer wegvalt',
      'De initialen op het logo kiezen hun kleur op basis van de twee helften samen, met een randje in de tegenkleur',
      'Daardoor blijven ze leesbaar op elke combinatie, ook op blauw-wit of geel-zwart',
    ],
  },
  {
    version: '0.23.1',
    date: '2026-09-23',
    title: 'Je kern als kaarten, of als tabel',
    items: [
      'Nieuwe kaartweergave van je kern: per linie, met één stip voor de toestand en de kwaliteit groot',
      'Elke kaart toont alleen wat er nu toe doet — vorm, vermoeidheid, een contract dat afloopt, een groeispurt',
      'De tabel van zeventien kolommen blijft bestaan voor wie wil sorteren en vergelijken; je schakelt met één klik',
      'Je keuze blijft bewaard, ook als je het spel sluit',
    ],
  },
  {
    version: '0.23.0',
    date: '2026-09-23',
    title: 'Overal zien wat iets oplevert',
    items: [
      'Elk bouwproject toont nu wat het je oplevert: toeschouwers, kantine, jeugdleden — én wat het aan vaste kosten kost',
      'De tribuneschuif rekent live mee: sleep en je ziet meteen hoeveel plaatsen en hoeveel onderhoud erbij komt',
      'Op de transfermarkt staat per speler wat hij aan je beste elf toevoegt; vaak is dat niets, en dan betaal je voor de bank',
      'Het weekrapport opent met kaartjes: resultaat, uitslag, publiek, records en mijlpalen in één oogopslag',
      'Spelers hebben één gekleurde stip voor hun toestand in plaats van vijf iconen door elkaar',
      'De speelknoppen en je saldo staan nu in een vaste balk onderaan, altijd in beeld, met hoeveel er op je wacht',
      'De tabelkop scrolde door de tabel heen; de menubalken blijven nu netjes bovenaan en de kopbalk schuift gewoon weg',
      'Feitenlijstjes braken hun waarden over drie regels af; die hebben nu ruimte en een rustige lijn ertussen',
    ],
  },
  {
    version: '0.22.1',
    date: '2026-09-23',
    title: 'De handleiding wees nog naar de oude menu\'s',
    items: [
      'Na de herindeling verwees de handleiding nog naar "Club › Financiën" en "Club › Cijfers", die daar niet meer staan',
      'Nieuw: "Waar vind ik wat?" zet per menu op een rij wat je er terugvindt',
      'Ook de taakbeschrijvingen wijzen nu naar het juiste scherm (Geld › Sponsors in plaats van "tab Sponsors")',
      'Op Financiën staan de investeerderskaart en de abonnementen naast elkaar in plaats van elk over de volle breedte',
    ],
  },
  {
    version: '0.22.0',
    date: '2026-09-23',
    title: 'Je eigen kleuren, en cijfers die zeggen wat ze doen',
    items: [
      'Bij een nieuw spel kies je een kleurenschema; die kleuren lopen door de hele app, van je logo tot je knoppen',
      'Elk schema is doorgerekend op leesbaarheid: geel wordt oker waar tekst nodig is, de echte clubkleur blijft op je logo en de band',
      'Bestaande spellen krijgen automatisch het schema dat het dichtst bij hun oude clubkleuren ligt',
      'De kopbalk is opnieuw gemaakt: logo en clubnaam bijna twee keer zo groot, met je clubkleuren als band erboven',
      'De seizoensbalk verhuisde van de kopbalk naar de kalender, waar ze ruimte heeft en waar je ze zoekt',
      'Nieuw op Personeel: per persoon staat er nu in kaartjes wát hij oplevert — teamsterkte, blessurekans, toeschouwers, euro\'s',
      'Bij kandidaten is dat het verschil met wie je nu hebt, doorgerekend met dezelfde formules waarmee het spel rekent',
      'Op een breed scherm valt het dashboard zelf in twee kolommen, zodat je minder scrolt',
      'De opstelling is een veld geworden met je kern ernaast: klik wie eruit moet, klik wie erin komt',
      'Strategie staat in drie kolommen en de sponsorplaatsen als tien tegels in plaats van drie uitgerekte blokken',
      'Inklappijltjes zijn echte ronde knoppen geworden in plaats van een grijs driehoekje van zes pixels',
    ],
  },
  {
    version: '0.21.1',
    date: '2026-09-23',
    title: 'De week begint met wat er op je ligt te wachten',
    items: [
      '"Deze week" staat nu bovenaan over de volle breedte: het eerste wat je bekijkt, niet een kaartje in de zijkolom',
      'De beslissing van de week zit erin als eerste regel, met de knop erbij, in plaats van in een aparte kaart',
      'Elke regel zegt er nu bij wat er op het spel staat: waarom het dringend is, of wanneer het vervalt',
      'Rood is voor echte problemen; de gewone weekbeslissing krijgt de clubkleur zodat de rode streep iets blijft betekenen',
      'De kopbalk is herbouwd: de vijf kerncijfers die het dashboard al groot toont staan er niet meer dubbel',
      'Nieuw in de kopbalk: een seizoensbalk met de 52 weken, elke speeldag als streepje, de winterstop en de transferperiodes als band',
      'Daarmee zie je in één blik of het venster open is, hoeveel weken tot de volgende match, en wanneer de eindstand valt',
      'Op een telefoon is de kopbalk ongeveer gehalveerd, zodat je meteen bij je werklijst uitkomt',
    ],
  },
  {
    version: '0.21.0',
    date: '2026-09-23',
    title: 'Een dashboard in plaats van een spreadsheet',
    items: [
      'Het dashboard is van nul herbouwd vanuit het oogpunt van een eigenaar: links geld, posten en wedstrijd, rechts wat je aandacht vraagt',
      'Saldo, resultaat van de week en de prognose over acht weken staan nu groot bovenaan',
      'Publiek, sponsors en je clubscores tonen niet alleen een cijfer maar ook wat dat cijfer concreet doet',
      'Nieuws is naar onderaan verhuisd; je langetermijndoel en de seizoensdoelen staan nu bij Club › Doelen',
      'Nieuwe look in de hele app: geen kaderlijnen meer, meer ruimte, zwaardere cijfers en rustiger tabellen',
      'Het menu is opnieuw ingedeeld: Geld kreeg een eigen tab, en Club heeft geen tien subtabs meer',
      'Tooltips verschijnen voortaan groot en leesbaar rechtsonder in beeld in plaats van als browsertekstje bij je muis',
      'Getalvelden hebben echte min- en plusknoppen die je kunt raken, met doorlopen bij ingedrukt houden en shift voor stappen van tien',
      'Op elk taakscherm (kantine, clubwinkel, tactiek, sponsors, …) kies je nu ter plekke wie de taak doet',
      'De startlijst voor nieuwe eigenaars is een strook geworden in plaats van een half scherm',
    ],
  },
  {
    version: '0.20.1',
    date: '2026-09-23',
    title: 'Twee voordelen die in de praktijk niets deden',
    items: [
      'De vrijwilligersfactor zat vast op een hard plafond waar clubs vanaf week één al tegenaan zaten',
      'Daardoor was elke extra vrijwilliger — en dus ook de +40% van de coöperatie — letterlijk niets waard',
      'Het plafond is nu een afvlakkende curve: een extra paar handen levert altijd iets op, alleen steeds minder',
      'Een onderbemande club wordt nog even hard afgestraft als vroeger',
      'De coöperatie geeft nu echt +40% vrijwilligers en de lokale figuur +30%, zoals de tekst al beloofde',
      'De stadionnaam van de aannemer volgt nu ook je reputatie en het prijspeil, niet alleen je reeks',
      'Dat contract wordt nooit heronderhandeld, dus het wordt elk seizoen automatisch herbekeken',
    ],
  },
  {
    version: '0.20.0',
    date: '2026-09-23',
    title: 'Drie investeerders, drie verschillende spellen',
    items: [
      'De stadionnaam van de aannemer groeit mee met je reeks in plaats van vast te staan op €600/week',
      'Bij de aannemer zijn bouwwerken ook een kwart sneller klaar, en mag je drie werven tegelijk open hebben',
      'Het fonds neemt voortaan ook 20% van je prijzengeld, en daar valt niet aan te ontkomen',
      'Het fonds tekent zelf voor een stevig bod op een jonge speler; jij hoort het achteraf',
      'De promotie-eis van het fonds keert terug: de klok begint opnieuw bij elke promotie',
      'De coöperatie kan elk seizoen een ledenronde houden, die groeit met je supporters, reputatie en sfeer',
      'Bij de coöperatie tellen vrijwilligers zwaarder door: het plafond ligt daar op 1,35 in plaats van 1,15',
      'Je financiënscherm vertelt nu altijd wat jouw investeerder voor je club betekent',
    ],
  },
  {
    version: '0.19.0',
    date: '2026-09-23',
    title: 'Twee snelheden, vooruitkijken en beslissingen die blijven hangen',
    items: [
      'Nieuwe knop "Tot de volgende match": speelt de rustige weken achter elkaar en stopt zodra er iets is dat jou nodig heeft',
      'Na het doorspelen krijg je één venster met het saldo, de records, de mijlpalen en het nieuws van die weken',
      'Kasprognose op Financiën: tot acht weken vooruit, met een waarschuwing als je onder nul zou duiken',
      '"Waar kwam het vandaan": per post wat het weer, de opkomst, je prijzen en je vrijwilligers deze week uithaalden',
      'Twintig nieuwe weekmomenten, van de frietketel tot de scout achter het doel — 36 situaties in totaal',
      'Het moment "Je beste man is op" kon nooit gebeuren (het vroeg vermoeidheid boven 70); dat is rechtgezet',
      'Abonnementen: één keer per seizoen, geld ineens in kas, en daarna betalen die mensen niet meer aan de kassa',
      'Bij een nieuw sponsorcontract kies je zelf de looptijd: langer tekenen betaalt beter, maar schuift niet mee bij promotie',
    ],
  },
  {
    version: '0.18.0',
    date: '2026-09-23',
    title: 'Een levende reeks en een carrière met een boog',
    items: [
      'Elke club in elke reeks heeft nu een eigen bestuur: budget, ambitie, momentum, accommodatie en jeugdwerking',
      'Eén keer per zomer beslist elke club wat ze doet — versterken, bouwen, jeugd uitbreiden, besparen of de boeken neerleggen',
      'Wie vorig jaar investeerde, staat er dit jaar beter voor: de sterktes in je reeks zijn geen vaste getallen meer',
      'Op het competitiescherm zie je per club haar sterkte, ambitie, werking en wat ze vorige zomer besliste',
      'Je kiest één keer een langetermijndoel: acht doelen, van "naar 2de nationale" tot "hoog én gezond"',
      'Dat doel staat de hele carrière op je overzicht, met de actuele stand, en krijgt een plek in je museum zodra het lukt',
      'Vijf eigenaarsniveaus met elk één concreet voordeel: lagere rente, een derde bouwproject, meer sponsorprospecten, meer subsidie',
      'Keuzes werken door: een sponsorruzie loopt over drie stappen, een verkochte speler kom je later tegen, geldzorgen slepen aan',
      'Een ambitieuze rivaal met een sterke jeugdwerking kan je mooiste belofte wegkapen',
      'Nieuw in je museum: de clubkroniek met alles wat de moeite is om na te vertellen',
      'Onder de motorkap: weekmomenten, gebeurtenissen en nieuwsberichten zijn nu data in plaats van code',
    ],
  },
  {
    version: '0.17.2',
    date: '2026-09-23',
    title: 'Het weekmoment als venster',
    items: [
      'Het weekmoment verschijnt nu als venster zodra je het weekrapport sluit, zodat je het niet meer mist',
      'Het gevolg van je keuze staat in hetzelfde venster, niet meer als kort meldinkje onderaan',
      '"Later beslissen" sluit het venster; op je overzicht blijft een kader met een knop om alsnog te beslissen',
      'Dezelfde situatie komt minstens 12 weken niet terug (ze kwam soms elke week opnieuw)',
    ],
  },
  {
    version: '0.17.1',
    date: '2026-09-23',
    title: 'Jij beslist wie er speelt',
    items: [
      'Haal je iemand uit je basiself, dan blijft die plaats open: je trainer vult niet meer vanzelf aan',
      'Met een open plaats kun je niet naar de volgende week, met uitleg welke linie het betreft',
      'De spelerstabellen zijn in- en uitklapbaar; bank en niet-beschikbaar staan standaard dicht',
    ],
  },
  {
    version: '0.17.0',
    date: '2026-09-23',
    title: 'Basiself onder controle en evenementen voor elke reeks',
    items: [
      'Twee knopjes per speler: ★ vastzetten in de basis, 🪑 deze week op de bank houden',
      'Vastzetten in een volle linie verdringt nu de zwakste vastgezette speler in plaats van te weigeren',
      'Spelers springen meteen naar de juiste tabel en de tellers (11/11 en per linie) lopen mee',
      'Evenementen schalen mee: opbrengst met je club en de inflatie, kosten met de inflatie en +12% per reeks',
      'Vijf nieuwe evenementen die vrijkomen in hogere reeksen, van het sponsorontbijt tot een internationaal wintertornooi',
      'Het weekmoment valt beter op: het staat nu ook bij Aandacht en in de tip op de knop "Volgende week"',
    ],
  },
  {
    version: '0.16.1',
    date: '2026-09-23',
    title: 'Scherpere volumekorting op de tribune',
    items: [
      'De prijs per zitje zakt agressiever én versnelt: elke volgende honderd zitjes kosten minder dan de vorige',
      '€360 per extra zitje rond de 100 plaatsen, €210 rond de 1.000 en €80 rond de 2.000',
      'De uitklapbare prijstabel bij de tribune is weg: de schuifregelaar zegt het al',
    ],
  },
  {
    version: '0.16.0',
    date: '2026-09-23',
    title: 'Bouwen op jouw maat',
    items: [
      'Bij de tribune kies je met een schuifregelaar hoeveel plaatsen erbij komen (100 tot 2.000)',
      'Hoe groter je bestelt, hoe goedkoper per zitje, en die korting versnelt: van ±€450 bij 100 plaatsen naar ±€215 bij 2.000 (−52%)',
      'Grotere werken duren langer: 4 tot 22 weken',
      'Zonnepanelen zijn een bouwproject geworden en duren 5 weken',
      'Er mogen twee bouwprojecten tegelijk lopen',
    ],
  },
  {
    version: '0.15.0',
    date: '2026-09-23',
    title: 'Nederlandse termen',
    items: [
      'Staff heet nu Personeel, overal: de tab, de lonen, de tooltips en de taken',
      'T1, T2 en T3 staan voluit: hoofdtrainer, assistent-trainer en conditietrainer',
      'Fanshop werd Clubwinkel, webshop werd webwinkel, de merchandisingverantwoordelijke werd winkelverantwoordelijke',
      'Boekingscategorieën in het Nederlands: clubartikelen, inkoop winkel, werking winkel en lonen personeel',
      'Clubrating werd Clubscore, dashboard werd overzicht, Vacant werd Niet ingevuld, FAQ werd veelgestelde vragen',
      'Voetbaltermen blijven: balbezit, counter, pressing, derby, transfer, scout, keeper, kern, ticketprijs',
    ],
  },
  {
    version: '0.14.0',
    date: '2026-09-23',
    title: 'Sterkere reeksen, duidelijkere selectie en doelpuntenmakers',
    items: [
      'Elke reeks ligt nu duidelijk boven de vorige: de zwakste ploeg van 2de nationale is steviger dan de zwakste van 3de',
      'Als promovendus start je onderaan: net gepromoveerde clubs (ook jij) zijn zwakker, net gedegradeerde sterker',
      'Selectie opgesplitst in basiself, bank en niet-beschikbaar, met een teller per linie tegenover je formatie',
      'Na elke wedstrijd zie je wie scoorde (met minuut) en wie er begon; doelpunten staan ook in je spelerstabel',
      'Bankleningen schalen mee met je reeks, je loonmassa en de inflatie',
      'Het nieuws in het weekrapport rolt trager binnen',
    ],
  },
  {
    version: '0.13.0',
    date: '2026-09-23',
    title: 'Derby, weekmoment en clubmuseum',
    items: [
      'Elke reeks heeft nu zijn eigen clubs: dorpsploegen in provinciale, profclubs bovenaan',
      'Eén echte aartsrivaal met een derby die telt: meer volk, meer kaarten, dubbel effect op de sfeer, en een onderlinge balans die blijft',
      'Het weekmoment: elke week één concrete beslissing voor de aftrap, met meteen gevolg',
      'Clubmuseum onder Club: titels, records, mijlpalen, erelijst en de mensen die er iets van maakten',
      'Passief spelen is scherper afgestraft: een club waar weken niets beslist wordt, verliest sfeer, reputatie en sponsortevredenheid',
    ],
  },
  {
    version: '0.12.0',
    date: '2026-09-23',
    title: 'Een echte jeugdwerking van bij de start',
    items: [
      'Je club begint met jeugdploegen (U7 tot U17) én een jeugdcoördinator in dienst',
      'Elke ploeg bindt twee vrijwilligers: evenementen kunnen alleen de vrije vrijwilligers gebruiken',
      'Je accommodatie begrenst het aantal ploegen; kunstgras, verlichting en het opleidingscentrum maken plaats',
      'Te weinig begeleiding remt de instroom en brandt je vrijwilligers op',
      'Een jeugdcoördinator aanwerven vraagt 3 ploegen, de jeugdsponsor ook',
      'Elke ploeg kost werkingsgeld en verhoogt de aansluiting bij de bond',
    ],
  },
  {
    version: '0.11.0',
    date: '2026-09-23',
    title: 'De seizoensopening',
    items: [
      'Elk seizoen begint met een openingsscherm: affiche, voorbeschouwing van de pers, wat er deze zomer gebeurde en wie er uit de jeugd doorstroomt',
      'De persconferentie: spreek je ambitie uit (voeten op de grond, meedoen voor de prijzen of wij worden kampioen)',
      'Die keuze verandert meteen de stemming bij supporters, spelers en sponsors, en wordt op het einde van het seizoen afgerekend in geld en reputatie',
      'Het bestuur legt drie doelen op tafel, één per categorie van je clubscore, elk met een premie',
      'De doelen staan het hele seizoen op je overzicht met een voortgangsbalk, en de afrekening staat in het seizoensrapport',
    ],
  },
  {
    version: '0.10.3',
    date: '2026-09-23',
    title: 'Nieuws en afwachting rollen mee binnen',
    items: [
      'De nieuwsberichten en de lijst "In afwachting" verschijnen regel per regel, samen met de cijfertellers',
      'Hele regels tegelijk, geen letter-per-letter getik',
      'Staat de animatie uit bij Opslaan, of vraagt je systeem minder beweging, dan staat alles er meteen',
    ],
  },
  {
    version: '0.10.2',
    date: '2026-09-23',
    title: 'Rustiger weekanimatie en een zichtbare premie',
    items: [
      'De animatie voor het weekrapport duurt twee keer zo lang: de bal rolt trager en de drie tussentitels blijven staan',
      'De cijferrollers tellen ongeveer 20% trager op, post per post',
      'Kampioenen- en promotiepremie staan nu apart onder "premies" in plaats van tussen de meevallers',
      'De premie staat in het weekrapport, in het seizoensrapport, bij Club › Cijfers en in je clubgeschiedenis; de kalender toont vooraf wat de titel waard is',
    ],
  },
  {
    version: '0.10.1',
    date: '2026-09-23',
    title: 'Herstel van opslagbestanden',
    items: [
      'Opslagbestanden van een tussenversie misten de clubrecords, waardoor "Volgende week" niets meer deed',
      'Elk bestand wordt nu bij het laden aangevuld met alles wat het nog niet kent',
      'Gaat er toch iets mis tijdens een week, dan krijg je een melding in plaats van een knop die niets doet',
    ],
  },
  {
    version: '0.10.0',
    date: '2026-09-23',
    title: 'Promotie verandert alles: inkomsten én kosten',
    items: [
      'Kampioenen- en promotiepremie: bescheiden in de amateurreeksen, echt prijzengeld vanaf de Challenger Pro Liga',
      'Na promotie vragen spelers 14% en personeel 10% meer; na degradatie wordt er neerwaarts onderhandeld',
      'Aansluiting bij de bond en verzekeringen schalen met je reeks, de gemeentesubsidie ook',
      'De richtprijzen in de fanshop volgen het niveau van je reeks',
    ],
  },
  {
    version: '0.9.9',
    date: '2026-09-23',
    title: 'Wedstrijdpremies en sponsors na promotie',
    items: [
      '30% van de spelersvergoeding is een wedstrijdpremie: in een week zonder wedstrijd betaal je die niet',
      'Een zege kost een winstpremie van 12% aan de basiself',
      'Na promotie bieden sponsors spontaan een hoger contract aan en stijgt hun tevredenheid',
      'Na degradatie zakt de tevredenheid van je sponsors',
    ],
  },
  {
    version: '0.9.8',
    date: '2026-09-22',
    title: 'Teller post per post, jong talent en promotie in het rapport',
    items: [
      'De bedragen in het weekrapport tellen post per post op, elk met een klein accent als ze landen',
      'Jonge spelers groeien sneller (tot 19 jaar +30%, tot 21 jaar +15%) en worden minder snel moe',
      'Oudere spelers raken sneller vermoeid',
      'Het seizoensrapport toont het echte resultaat: kampioen, promotie, degradatie of behoud, met de reeks waarin je volgend seizoen speelt',
    ],
  },
  {
    version: '0.9.7',
    date: '2026-09-22',
    title: 'Spanning per week: records, reeksen en onthulling',
    items: [
      'De animatie bouwt op met drie momenten en een voortgangsbalk',
      'De uitslag springt eruit zodra het rapport opent, daarna lopen de bedragen op',
      'Clubrecords: opkomst, beste week, langste reeks en meeste supporters, met een melding als er een sneuvelt',
      'Een lopende reeks (drie zeges of vier ongeslagen) staat bij de uitslag',
    ],
  },
  {
    version: '0.9.6',
    date: '2026-09-22',
    title: 'Eerlijke fanshopmarge en een echt seizoenseinde',
    items: [
      'Fanshop: inkoop van verkochte artikelen en vaste werkingskosten staan apart, zodat je je echte marge ziet',
      'De knop toont wanneer het de laatste speeldag is of wanneer je het seizoen afsluit',
      'Seizoensrapport met eindstand, resultaten, inkomsten tegenover vorig seizoen, supporters, jeugd en mijlpalen',
    ],
  },
  {
    version: '0.9.5',
    date: '2026-09-22',
    title: 'Mijlpalen, tellers en thuisvoordeel',
    items: [
      'Geschiktheid van een staflid voor een taak staat in sterren',
      'Mijlpalen: elf momenten om naar toe te werken, met een beloning en een plek bovenaan het weekrapport',
      'De bedragen in het weekrapport tellen op als een teller',
      'Thuis spelen geeft een klein voordeel; uit spelen een klein nadeel',
      'Supporters groeien sneller als je ploeg goed draait, dus succes bouwt op zichzelf verder',
    ],
  },
  {
    version: '0.9.4',
    date: '2026-09-22',
    title: 'Bank, terugverdientijd en scherpere wedstrijden',
    items: [
      'Een kredietaanvraag gaat naar de bank: antwoord volgt een week later (een noodlening staat er wel meteen op)',
      'Zonnepanelen kosten wat bij jouw complex hoort en zijn na ongeveer drie seizoenen terugverdiend; de ploegbus idem',
      'Wedstrijden zijn scherper: staff, sfeer en vorm wegen minder door dan de kwaliteit van je spelers, en tegenstanders hebben ook een trainer',
      'De meldingen bij Aandacht zijn links naar het juiste scherm',
    ],
  },
  {
    version: '0.9.3',
    date: '2026-09-22',
    title: 'Specialisatie, menu en eerste stappen',
    items: [
      'Een staflid werkt buiten zijn vakgebied op een lager niveau en kan 1 tot 4 taken aan',
      'Hamburgermenu rechtsboven met de handleiding en het opslaan',
      'Handleiding met veelgestelde vragen',
      'Startlijst "Eerste stappen" op het overzicht voor een nieuwe eigenaar',
      'Kantineverbruik realistischer: ongeveer 2 consumpties per bezoeker in plaats van 6',
      'De ploegbus is een investering geworden en ontgrendelt pas dan de bussponsor',
    ],
  },
  {
    version: '0.9.2',
    date: '2026-09-22',
    title: 'Winterstop, kopbalk en duidelijkere boekingen',
    items: [
      'Clubscore staat naast de clubnaam in plaats van eronder',
      'Winterstop is duidelijk zichtbaar: in de kopbalk, op het overzicht en in het weekrapport',
      'Tijdens de winterstop draait de kantine op halve kracht',
      '"Concessies" heet nu "horeca concessies" in alle overzichten',
      'Wedstrijdkosten benoemen of het om een thuis- of uitwedstrijd gaat',
    ],
  },
  {
    version: '0.9.1',
    date: '2026-09-22',
    title: 'Delegeren, sponsorplaatsen en heldere ticketinkomsten',
    items: [
      'Elke taak krijgt een keuzelijst bij Staff: kies per taak wie ze doet',
      'Drie nieuwe taken: jeugdwerking (lidgeld), belasting en blessurepreventie, onderhoud en bouwprojecten',
      'Ticketinkomsten staan nu bruto in de boeken, met het aandeel van de bezoekers en de bond (8%) als aparte kost',
      'Kopbalk is klikbaar: klassement, hoofdsponsor, saldo, teamsterkte en datum brengen je naar het juiste scherm',
      'Meer soorten sponsoring: mouw, ploegbus, evenementen, schermen in de kantine en de wedstrijdbal; de sectoren zijn evenwichtiger verdeeld',
      'Een uitgeleende speler kun je gewoon een nieuw contract geven',
    ],
  },
  {
    version: '0.9.0',
    date: '2026-09-22',
    title: 'Onderhandelen, weekcijfers en scherpere balans',
    items: [
      'Transferperiode staat duidelijk open of gesloten bovenaan de tab Transfers',
      'Loononderhandelingen lopen vast als je blijft laagbieden: hij vraagt meer, verliest moraal en haakt na drie pogingen af',
      'Cijfers ook per week, met de opbrengst per bron; horeca staat nu overal tussen de inkomsten',
      'Clubscore staat in de kopbalk naast de clubnaam',
      'Je kiest je eigen clubnaam bij de start',
      'Nieuw bouwproject: scorebord (meer sfeer, bordsponsors betalen meer)',
      'Meer staf vraagt eerst de juiste infrastructuur (analist wifi, kantineverantwoordelijke een degelijke kantine, ...)',
      'Vrijwilligers op een menselijke schaal: ongeveer 12 in plaats van 28, evenementen vragen er 3 tot 14',
      'Sponsornaam en sector kloppen nu ook in oude opslagbestanden',
      'Passief spelen is duidelijk moeilijker gemaakt',
    ],
  },
  {
    version: '0.8.0',
    date: '2026-09-22',
    title: 'Kern, contracten, horeca en cijfers',
    items: [
      'Transfers: je laatste doelman blijft, elke linie houdt een reserve en je zakt nooit onder 16 spelers',
      'Contracten verlengen met een loonvoorstel dat de moraal beïnvloedt (Ploeg › Contracten)',
      'Kantineprijzen per artikel en horecaconcessies met onderhandelde marge (Club › Horeca)',
      'Cijfers per seizoen: tickets, consumpties, merchandising en leden (Club › Cijfers)',
      'Populariteit weegt op alle inkomsten; wat men voor een shirt betaalt, stijgt mee',
      'Spelersrollen: kapitein, strafschop- en hoekschopnemer',
      'Delegeren per deeltaak: training, opstelling, tactiek, spelersrollen, transfers, horeca',
      'Vaste menubalk, automatisch opslaan van invoervelden, 11/11-teller en tooltips',
      'Nieuwe infrastructuur: wifi, sanitair, parking; onderhoudsniveau en zonnepanelen',
      'Vrijwilligers komen en gaan; evenementen vragen meer volk',
      'Logboek van je beslissingen en antwoorden op de tab Overzicht',
    ],
  },
  { version: '0.7.0', date: '2026-09-22', title: 'Fanshop en leeftijdscurve', items: ['Fanshop met assortiment en prijzen', 'Vloeiende leeftijdscurve voor de evolutie van spelers'] },
  { version: '0.6.0', date: '2026-09-22', title: 'Weekrapport en kalender', items: ['Animatie en weekrapport', 'Seizoenskalender', 'Verkopen, te koop zetten, uitlenen en huren'] },
  { version: '0.5.0', date: '2026-09-21', title: 'Blessures, kaarten en herstel', items: ['Kaarten en schorsingen', 'Forfait', 'Herstelmechanisme en extra staff'] },
  { version: '0.4.0', date: '2026-09-21', title: 'Opleiding, financiën en invloeden', items: ['Opleidingen voor staff', 'Weekfinanciën', 'Tab Invloeden', 'Vermoeidheid en scouting'] },
  { version: '0.3.0', date: '2026-09-20', title: 'Strategie en jeugd', items: ['Strategietab met spelplannen', 'Lidgeld jeugd'] },
  { version: '0.2.0', date: '2026-09-20', title: 'Staff, sponsors en evenementen', items: ['Meer staff en delegeren', 'Sponsorwerving', 'Evenementen met vrijwilligers'] },
  { version: '0.1.0', date: '2026-09-19', title: 'Eerste versie', items: ['Club, investeerder, competitie, transfers en financiën'] },
];
